# These are supported funding model platforms

github: [SURJO99exe]
patreon: # Replace with your patreon username if you have one
open_collective: # Replace with your open_collective username
ko_fi: # Replace with your ko_fi username
tidelift: # Replace with your tidelift platform/package
community_bridge: # Replace with your community_bridge project name
liberapay: # Replace with your liberapay username
issuehunt: # Replace with your issuehunt username
lfx_crowdfunding: # Replace with your lfx_crowdfunding project name
custom: # Replace with a single custom sponsorship URL
