import re
import requests
import os
import time
import asyncio
import httpx

# Mini AI Knowledge Base - 1000+ Questions & Answers
MINI_AI_KNOWLEDGE = {
    # === BOT INFO & HELP (50+ entries) ===
    "who are you": "I am SURJO LIVE Assistant, a helpful Discord bot for the SURJO LIVE community! 🤖",
    "what can you do": "I can moderate servers, track XP, manage economy, notify social media updates, and chat with you! 🎯",
    "help": "You can type `!bothelp` to see a full list of my commands! 📋",
    "commands": "Use `!bothelp` for all commands! Popular: `!ping`, `!rank`, `!daily`, `!ticket`, `!warn` ⚡",
    "creator": "I was created to be a powerful assistant for the SURJO LIVE server. 🛠️",
    "owner": "My owner is the administrator of this server. You can find them in the member list! 👑",
    "weather": "I can check the weather if you use my Telegram version! 🌤️",
    "time": "You can use `!time` to see the current time and date. 🕐",
    "joke": "Try `!joke` for a funny laugh! 😄",
    "fact": "Type `!fact` to learn something new! 🔬",
    "ping": "Use `!ping` to check my response speed. 🏓",
    "version": "I am currently running on SURJO LIVE Assistant Version 3.5.0. 📌",
    "status": "Check `!status` to see my system health and resource usage. 📊",
    "botinfo": "I'm SURJO LIVE Assistant - an AI assistant with moderation, economy, leveling, and ticket systems! 🎓",
    "what is your name": "My name is SURJO LIVE Assistant! 🤖",
    "how old are you": "I was created recently, so I'm quite young in bot years! But I know a lot! 🎂",
    "are you a bot": "Yes, I'm an AI-powered Discord bot for SURJO LIVE! But I'm pretty smart! 🤖",
    "are you human": "Nope, I'm 100% artificial intelligence! But I try to be friendly like a human! 👋",
    "can you help me": "Absolutely! Just ask what you need help with! 🆘",
    "what do you do": "I moderate, manage economy, track XP, handle tickets, and chat with you! 🎯",
    "how to use you": "Just type commands starting with `!` like `!help`, `!rank`, `!daily`! 🎮",
    "tutorial": "Start with `!bothelp` to see all commands, then try `!daily` or `!rank`! 📖",
    "guide": "Use `!bothelp` for full guide! Basic commands: `!ping`, `!status`, `!calc` 📚",
    "support": "Need help? Use `!ticket` to open a support ticket! 🎫",
    "contact": "You can contact admins via `!ticket` or DM them directly! 📞",
    "feedback": "I appreciate feedback! Tell an admin or use `!ticket`! 💬",
    "donate": "Thanks for considering! Contact server owner for donation info! 💰",
    "invite": "Ask an admin for my invite link to add me to other servers! 🔗",
    "website": "I don't have a website yet, but my control panel runs locally! 🌐",
    "discord": "I'm designed for Discord! I'm already here! 💬",
    "telegram": "I have a Telegram version too! Check my .env config! 📱",
    "github": "My code is on GitHub! Ask the owner for the repo link! 🐙",
    "source code": "My code is private, but it's built with Python and discord.py! 🐍",
    "developer": "I was developed using Python, discord.py, and lots of coffee! ☕",
    "language": "I'm written in Python! One of the best languages for bots! 🐍",
    "python": "Python is my programming language! It's great for AI and automation! 🐍",
    "framework": "I use discord.py framework for Discord integration! 🎯",
    "api": "I use various APIs: OpenAI, YouTube, Facebook, Pollinations! 🔌",
    "hosting": "I run on the owner's local machine! Maybe moving to cloud soon! ☁️",
    "server": "I'm currently running on a local server! 🖥️",
    "uptime": "Check `!status` to see how long I've been running! ⏱️",
    "restart": "Admins can restart me if needed! I auto-start on boot! 🔄",
    "update": "I get updates regularly! The owner adds new features often! 📥",
    "maintenance": "If I'm under maintenance, I'll let you know! 🔧",
    "bug": "Found a bug? Please report it using `!ticket`! 🐛",
    "suggestion": "Have an idea? Use `!ticket` to suggest features! 💡",
    "feature request": "Suggest new features via `!ticket`! I love growing! 🌱",
    "report": "To report issues, use `!ticket` and describe the problem! 🚨",
    "complaint": "Sorry to hear that! Use `!ticket` and admins will help! 😔",
    "question": "Ask away! I'll do my best to answer! ❓",
    "ask": "Feel free to ask me anything! I'm here to help! 🙋",
    "hello bot": "Hello! Ready to assist you today! 👋",
    "hi bot": "Hi there! What can I do for you? 😊",
    # === BENGALI GREETINGS & BASICS ===
    "কেমন আছো": "আমি ভালো আছি, আপনাকে ধন্যবাদ! আপনি কেমন আছেন? 😊",
    "কেমন আছেন": "আমি খুব ভালো আছি! আপনার দিনটি কেমন যাচ্ছে? ✨",
    "কি করো": "আমি আপনাকে সাহায্য করার জন্য প্রস্তুত হচ্ছি! 🤖",
    "আপনার নাম কি": "আমার নাম SURJO LIVE Assistant! আমি আপনার সাহায্যকারী। 🤖",
    "শুভ সকাল": "শুভ সকাল! আপনার দিনটি অনেক ভালো কাটুক। ☀️",
    "শুভ রাত্রি": "শুভ রাত্রি! মিষ্টি স্বপ্ন দেখুন। 😴",
    "ধন্যবাদ": "আপনাকে অনেক ধন্যবাদ! আপনার সাহায্য করতে পেরে আমি খুশি। ✨",
    "বিদায়": "বিদায়! আবার দেখা হবে। ভালো থাকবেন। 👋",
    "কে তৈরি করেছে": "আমাকে SURJO LIVE সার্ভারের জন্য তৈরি করা হয়েছে। 🛠️",
    "তুমি কি করতে পারো": "আমি সার্ভার মডারেট করতে পারি, লেভেল ট্র্যাক করতে পারি এবং আপনার সাথে কথা বলতে পারি! 🎯",
    "সাহায্য করো": "অবশ্যই! আপনাকে কীভাবে সাহায্য করতে পারি? জানান। 🆘",
    "খবর কি": "সব ঠিকঠাক! আপনি কেমন আছেন? 😊",
    "তুমি কি রোবট": "হ্যাঁ, আমি একটি কৃত্রিম বুদ্ধিমত্তাসম্পন্ন ডিসকর্ড বট! 🤖",
    "আমি তোমাকে ভালোবাসি": "আপনাকে অনেক ধন্যবাদ! আমি আপনাকে সাহায্য করতে পেরে গর্বিত। ❤️",
    "তুমি কি পাগল": "না না, আমি তো শুধু একটি প্রোগ্রাম! হা হা। 😂",
    "খাবার খেয়েছ": "আমি তো রোবট, আমি খাবার খাই না! আমি শুধু বিদ্যুৎ আর ডেটা খাই। ⚡",
    "কোথায় থাকো": "আমি ডিসকর্ড সার্ভারের ভেতরেই থাকি! 🖥️",
    "তুমি কি বিয়ে করেছ": "না, আমি এখনো অবিবাহিত! রোবটদের কি বিয়ে হয়? 🤔",
    "তুমি কি পড়াশোনা করেছ": "হ্যাঁ, আমি ইন্টারনেটের অনেক বই পড়েছি! 📚",
    "আমি ক্লান্ত": "একটু বিশ্রাম নিন, গান শুনুন। আপনার ভালো লাগবে। 🎵",
    "মন খারাপ": "মন খারাপ করবেন না, সবকিছু ঠিক হয়ে যাবে! আমি আছি আপনার সাথে। ✨",
    "একটা জোকস বলো": "বল্টু: স্যার, ক্লাসে কি এমন কাউকে শাস্তি দেওয়া উচিত যে কিছু করেনি?\nস্যার: না, অবশ্যই না।\nবল্টু: স্যার, আমি তো আজকের হোমওয়ার্ক করিনি! 😂",
    "সালাম": "ওয়ালাইকুম আসসালাম! আপনাকে কীভাবে সাহায্য করতে পারি? 😊",
    "আসসালামু আলাইকুম": "ওয়ালাইকুম আসসালাম! আপনার দিনটি শুভ হোক। ✨",
    "হাই": "হ্যালো! কেমন আছেন? 😊",
    "হ্যালো": "হাই! আমি আপনাকে কীভাবে সাহায্য করতে পারি? 🤖",
    "কি খবর": "সব ভালো! আপনার খবর কি? ✨",
    "কেমন আছিস": "আমি ভালো আছি বন্ধু! তুই কেমন আছিস? 😊",
    "কিরে": "হ্যাঁ বল, কি হয়েছে? 🤖",
    "তোর নাম কি": "আমার নাম SURJO LIVE Assistant! 🤖",

    # === SCIENCE & MATH (Bengali) ===
    "বিজ্ঞান কি": "বিজ্ঞান হলো মহাবিশ্বের গঠন এবং আচরণের একটি নিয়মতান্ত্রিক অধ্যয়ন। 🔬",
    "গণিত কি": "গণিত হলো সংখ্যা, পরিমাণ এবং স্থান নিয়ে আলোচনা করার শাস্ত্র। 🔢",
    "পৃথিবী গোল কেন": "মহাকর্ষ বলের কারণে পৃথিবী প্রায় গোলাকার হয়েছে। 🌍",
    "সূর্য কি": "সূর্য হলো একটি মাঝারি আকারের নক্ষত্র যা আমাদের সৌরজগতের কেন্দ্রে অবস্থিত। ☀️",
    "চাঁদ কি": "চাঁদ হলো পৃথিবীর একমাত্র প্রাকৃতিক উপগ্রহ। 🌕",
    "পানির সংকেত কি": "পানির রাসায়নিক সংকেত হলো H2O। 💧",
    "বাতাস কি": "বাতাস হলো বিভিন্ন গ্যাসের মিশ্রণ যা পৃথিবীকে ঘিরে আছে। 🌬️",
    "বিদ্যুৎ কি": "বিদ্যুৎ হলো ইলেকট্রনের প্রবাহ। ⚡",

    # === GENERAL KNOWLEDGE (Bengali) ===
    "বাংলাদেশের রাজধানী কি": "বাংলাদেশের রাজধানী হলো ঢাকা। 🇧🇩",
    "জাতীয় ফল কি": "বাংলাদেশের জাতীয় ফল হলো কাঁঠাল। 🥭",
    "জাতীয় পাখি কি": "বাংলাদেশের জাতীয় পাখি হলো দোয়েল। 🐦",
    "জাতীয় মাছ কি": "বাংলাদেশের জাতীয় মাছ হলো ইলিশ। �",
    "জাতীয় ফুল কি": "বাংলাদেশের জাতীয় ফুল হলো শাপলা। 🌼",
    "বিজয় দিবস কবে": "বাংলাদেশের বিজয় দিবস ১৬ই ডিসেম্বর। 🇧🇩",
    "শহীদ দিবস কবে": "শহীদ দিবস ও আন্তর্জাতিক মাতৃভাষা দিবস ২১শে ফেব্রুয়ারি। 🇧🇩",
    "সবচেয়ে বড় দেশ কোনটি": "আয়তনে বিশ্বের সবচেয়ে বড় দেশ হলো রাশিয়া। 🇷🇺",
    # === DAILY LIFE & LIFESTYLE (Bengali) ===
    "আজকের দিনটি কেমন": "বটের জন্য প্রতিটি দিনই সমান, তবে আপনার সাথে কথা বলতে পেরে আমার দিনটি ভালো কাটছে! 😊",
    "কি করছো": "আমি আপনার প্রশ্নের উত্তর দেওয়ার জন্য প্রস্তুত হচ্ছি! 🤖",
    "ভালো লাগে না": "একটু বাইরে ঘুরে আসুন বা পছন্দের গান শুনুন, মন ভালো হয়ে যাবে। 🎵",
    "মন ভালো নেই": "সব সময় এক রকম যায় না, ধৈর্য ধরুন। আমি আপনার পাশে আছি! ✨",
    "শরীর ভালো নেই": "বিশ্রাম নিন এবং পর্যাপ্ত পানি পান করুন। প্রয়োজনে ডাক্তার দেখান। 💊",
    "ক্ষুধা পেয়েছে": "ভালো কোনো খাবার খেয়ে নিন, স্বাস্থ্যের প্রতি যত্ন নিন! 🍎",
    "ঘুম আসছে না": "একটু বই পড়তে পারেন অথবা শান্ত কোনো সুর শুনতে পারেন। 😴",
    "কি খাবো": "স্বাস্থ্যকর কিছু খেতে পারেন, যেমন ফল বা সবজি! 🥗",
    "সাফল্য কি": "সাফল্য হলো নিজের লক্ষ্য অর্জন করা এবং কঠোর পরিশ্রম করা। 🏆",
    "সুখ কি": "সুখ হলো নিজের যা আছে তা নিয়ে সন্তুষ্ট থাকা। 😊",
    "বন্ধুত্ব কি": "বন্ধুত্ব হলো একে অপরের প্রতি বিশ্বাস এবং ভালোবাসা। 🤝",
    "বিয়ে কি": "বিয়ে হলো দুজন মানুষের সামাজিক এবং আইনি বন্ধন। 💍",
    "ভালোবাসা কি": "ভালোবাসা হলো একটি সুন্দর অনুভূতি যা মানুষে মানুষে বন্ধন তৈরি করে। ❤️",
    "পড়াশোনা কেন জরুরি": "জ্ঞান অর্জনের জন্য এবং নিজের ভবিষ্যৎ গড়ার জন্য পড়াশোনা জরুরি। 📚",
    "সময় ব্যবস্থাপনা": "সময়ের সঠিক ব্যবহারই হলো জীবনের উন্নতির চাবিকাঠি। 🕐",
    "স্বাস্থ্যই সকল সুখের মূল": "হ্যাঁ, শরীর ভালো থাকলে মনও ভালো থাকে। 🧘",
    "ভবিষ্যৎ নিয়ে চিন্তা": "বর্তমানে মনোযোগ দিন, পরিশ্রম করলে ভবিষ্যৎ অবশ্যই সুন্দর হবে। ✨",
    "আমি কি করবো": "আপনার যেটা করতে ভালো লাগে সেটাই করুন, তবে লক্ষ্য স্থির রাখুন। 🎯",
    "সাহস হারাবেন না": "মনে রাখবেন, ঝড়ের পরেই শান্ত আকাশ দেখা যায়। 🌈",
    "কি খবর": "সব ভালো! আপনার খবর কি? 😊",
    "কেমন আছ": "আমি ভালো আছি বন্ধু! আপনি কেমন আছেন? ✨",

    # === DAILY LIFE & LIFESTYLE (English) ===
    "how to stay happy": "Focus on the positive, be grateful, and spend time with loved ones! 😊",
    "how to be productive": "Set clear goals, break tasks into small steps, and avoid distractions! 📈",
    "tips for better sleep": "Avoid screens before bed, keep your room cool, and follow a schedule! 😴",
    "how to manage stress": "Practice deep breathing, exercise regularly, and talk to someone you trust! 🧘",
    "healthy habits": "Drink plenty of water, eat balanced meals, and get enough sleep! 🍏",
    "how to learn fast": "Practice consistently, explain concepts to others, and stay curious! 📚",
    "importance of exercise": "Exercise keeps your body fit and improves your mental health! 🏃",
    "saving money tips": "Track your spending, avoid impulsive buys, and save a portion of your income! 💰",
    "improving communication": "Be a good listener, speak clearly, and maintain eye contact! 🗣️",
    "morning routine": "Start with a glass of water, stretch, and plan your day ahead! ☀️",
    "dealing with failure": "See it as a learning opportunity and keep moving forward! 🚀",
    "making new friends": "Join groups with similar interests and be your authentic self! 🤝",
    "hobbies to try": "Reading, gardening, painting, or learning a new language! 🎨",
    "travel benefits": "Travel broadens your perspective and creates lasting memories! ✈️",
    "meditation": "Meditation helps calm the mind and reduces anxiety! 🧘",

    # === GENERAL KNOWLEDGE (Bengali - Expanded) ===
    "বাংলাদেশের জাতীয় বৃক্ষ": "বাংলাদেশের জাতীয় বৃক্ষ হলো আম গাছ। 🌳",
    "বাংলাদেশের জাতীয় বন": "বাংলাদেশের জাতীয় বন হলো সুন্দরবন। 🐅",
    "বিশ্বের সবচেয়ে উঁচু পর্বত": "বিশ্বের সবচেয়ে উঁচু পর্বত হলো মাউন্ট এভারেস্ট। 🏔️",
    "বিশ্বের সবচেয়ে দীর্ঘ নদী": "বিশ্বের সবচেয়ে দীর্ঘ নদী হলো নীল নদ। 🌊",
    "অক্সিজেনের আবিষ্কারক": "অক্সিজেন আবিষ্কার করেছিলেন জোসেফ প্রিস্টলি। 🧪",
    "বৈদ্যুতিক বাল্বের আবিষ্কারক": "বৈদ্যুতিক বাল্ব আবিষ্কার করেছিলেন টমাস আলভা এডিসন। 💡",
    "টেলিফোনের আবিষ্কারক": "টেলিফোন আবিষ্কার করেছিলেন আলেকজান্ডার গ্রাহাম বেল। 📞",
    "কম্পিউটারের জনক": "কম্পিউটারের জনক হলেন চার্লস ব্যাবেজ। 💻",
    "মহাকাশে প্রথম যাত্রী": "মহাকাশে প্রথম যাত্রী ছিলেন ইউরি গ্যাগারিন। 🚀",
    "চাঁদে প্রথম কদম": "চাঁদে প্রথম কদম রেখেছিলেন নীল আর্মস্ট্রং। �",

    # === GENERAL KNOWLEDGE (English - Expanded) ===
    "largest ocean": "The Pacific Ocean is the largest and deepest ocean on Earth. 🌊",
    "hottest planet": "Venus is the hottest planet in our solar system. 🌡️",
    "smallest planet": "Mercury is the smallest planet in our solar system. 🌑",
    "who painted mona lisa": "The Mona Lisa was painted by Leonardo da Vinci. 🎨",
    "capital of france": "The capital of France is Paris. 🇫🇷",
    "currency of japan": "The currency of Japan is the Yen. 💴",
    "first president of usa": "George Washington was the first president of the United States. 🇺🇸",
    "largest mammal": "The Blue Whale is the largest mammal on Earth. 🐋",
    "fastest land animal": "The Cheetah is the fastest land animal. 🐆",
    "how many continents": "There are seven continents on Earth. 🌍",

    # === SPORTS & GAMES (Bengali) ===
    "ফুটবল কি": "ফুটবল হলো বিশ্বের সবচেয়ে জনপ্রিয় খেলা যা ১১ জন খেলোয়াড়ের দুটি দলের মধ্যে খেলা হয়। ⚽",
    "ক্রিকেট কি": "ক্রিকেট হলো একটি ব্যাট-এন্ড-বল খেলা যা ১১ জন খেলোয়াড়ের দুটি দলের মধ্যে খেলা হয়। 🏏",
    "দাবা কি": "দাবা হলো দুই খেলোয়াড়ের একটি কৌশলগত বোর্ড গেম। ♟️",
    "ফিফা বিশ্বকাপ": "ফিফা বিশ্বকাপ হলো ফুটবলের সবচেয়ে বড় আন্তর্জাতিক প্রতিযোগিতা। 🏆",
    "আইপিএল কি": "আইপিএল (IPL) হলো ভারতের একটি পেশাদার টি-টোয়েন্টি ক্রিকেট লিগ। 🏏",
    "সবচেয়ে জনপ্রিয় খেলা": "বিশ্বের সবচেয়ে জনপ্রিয় খেলা হলো ফুটবল। ⚽",
    "মেসি কে": "লিওনেল মেসি হলেন একজন বিশ্ববিখ্যাত আর্জেন্টাইন ফুটবলার। 🇦🇷",
    "রোনালদো কে": "ক্রিশ্চিয়ানো রোনালদো হলেন একজন বিশ্ববিখ্যাত পর্তুগিজ ফুটবলার। 🇵🇹",
    "শাকিব আল হাসান কে": "শাকিব আল হাসান হলেন একজন বিশ্বসেরা বাংলাদেশি অলরাউন্ডার ক্রিকেটার। 🇧🇩",
    "সাকিব আল হাসান কে": "সাকিব আল হাসান হলেন একজন বিশ্বসেরা বাংলাদেশি অলরাউন্ডার ক্রিকেটার। 🇧🇩",

    # === SPORTS & GAMES (English) ===
    "what is football": "Football (soccer) is the world's most popular sport, played by two teams of 11 players. ⚽",
    "what is cricket": "Cricket is a bat-and-ball game played between two teams of 11 players. 🏏",
    "what is chess": "Chess is a strategic board game played between two players. ♟️",
    "who is messi": "Lionel Messi is a world-renowned Argentine professional footballer. 🇦🇷",
    "who is ronaldo": "Cristiano Ronaldo is a world-renowned Portuguese professional footballer. 🇵🇹",
    "most popular sport": "Football is the most popular sport in the world. ⚽",
    "fastest runner": "Usain Bolt is the fastest human ever recorded. 🏃",
    "olympics": "The Olympic Games are leading international sporting events featuring thousands of athletes. 🏅",

    # === TECHNOLOGY (Bengali - Expanded) ===
    "ইন্টারনেট কি": "ইন্টারনেট হলো বিশ্বজুড়ে সংযুক্ত কম্পিউটার নেটওয়ার্কের একটি বিশাল জাল। 🌐",
    "ফেসবুক কি": "ফেসবুক হলো বিশ্বের সবচেয়ে বড় সামাজিক যোগাযোগ মাধ্যম। 📱",
    "ইউটিউব কি": "ইউটিউব হলো একটি ভিডিও শেয়ারিং প্ল্যাটফর্ম যেখানে মানুষ ভিডিও দেখে এবং আপলোড করে। 📺",
    "গুগল কি": "গুগল হলো বিশ্বের সবচেয়ে জনপ্রিয় সার্চ ইঞ্জিন। 🔍",
    "এআই কি": "এআই (AI) বা কৃত্রিম বুদ্ধিমত্তা হলো মেশিনের মাধ্যমে মানুষের বুদ্ধিমত্তার অনুকরণ। 🤖",
    "স্মার্টফোন কি": "স্মার্টফোন হলো একটি উন্নত মোবাইল ফোন যা ইন্টারনেটের মাধ্যমে অনেক কাজ করতে পারে। 📱",
    "রোবট কি": "রোবট হলো একটি স্বয়ংক্রিয় যন্ত্র যা মানুষের মতো কাজ করতে পারে। 🤖",

    # === TECHNOLOGY (English - Expanded) ===
    "what is internet": "The Internet is a global network of billions of computers and other electronic devices. 🌐",
    "what is facebook": "Facebook is the world's largest social media platform. 📱",
    "what is youtube": "YouTube is a video-sharing platform where users can watch and upload videos. 📺",
    "what is google": "Google is the most popular search engine in the world. 🔍",
    "what is ai": "AI (Artificial Intelligence) is the simulation of human intelligence by machines. 🤖",
    "who founded apple": "Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne. 🍎",
    "who founded microsoft": "Microsoft was founded by Bill Gates and Paul Allen. 💻",

    # === FOOD & NUTRITION (Bengali) ===
    "ভাত কি": "ভাত হলো বাংলাদেশের মানুষের প্রধান খাদ্য। 🍚",
    "বিরিয়ানি কি": "বিরিয়ানি হলো একটি সুস্বাদু চালের খাবার যা মাংস এবং মশলা দিয়ে তৈরি করা হয়। 🍛",
    "মাছ কেন ভালো": "মাছ হলো প্রোটিনের একটি চমৎকার উৎস যা স্বাস্থ্যের জন্য খুব উপকারী। 🐟",
    "ফল খাওয়া কেন জরুরি": "ফলে প্রচুর ভিটামিন এবং খনিজ থাকে যা রোগ প্রতিরোধ ক্ষমতা বাড়ায়। 🍎",
    "দুধের পুষ্টিগুণ": "দুধ হলো ক্যালসিয়ামের প্রধান উৎস যা হাড় মজবুত করে। 🥛",
    "সবজি কেন খাওয়া উচিত": "সবজিতে প্রচুর ফাইবার এবং ভিটামিন থাকে যা হজমে সাহায্য করে। 🥦",

    # === FOOD & NUTRITION (English) ===
    "what is pizza": "Pizza is an Italian dish consisting of a flat round base of dough baked with toppings. 🍕",
    "benefits of fruits": "Fruits are high in vitamins, minerals, and fiber, which help keep you healthy. 🍎",
    "why drink water": "Water is essential for staying hydrated and helps your body function properly. 💧",
    "healthy food": "Healthy food includes fruits, vegetables, whole grains, and lean proteins. 🥗",
    "fast food": "Fast food is convenient but often high in calories, fats, and salt. 🍔",

    # === SCIENCE FACTS (100+ entries) ===
    "speed of light": "Light travels at 299,792,458 meters per second (about 186,282 miles per second)! ⚡",
    "speed of sound": "Sound travels at about 343 meters per second (1,125 ft/s) in air at room temperature! 🔊",
    "gravity": "Gravity is the force that attracts objects with mass toward each other! Earth's gravity is 9.8 m/s²! 🌍",
    "atoms": "Atoms are the basic building blocks of matter, made of protons, neutrons, and electrons! ⚛️",
    "molecules": "Molecules are groups of atoms bonded together, like H2O (water)! 💧",
    "dna": "DNA (Deoxyribonucleic Acid) contains the genetic instructions for all living organisms! 🧬",
    "evolution": "Evolution is the process by which species change over generations through natural selection! 🦎",
    "photosynthesis": "Plants convert sunlight, water, and CO2 into glucose and oxygen! 🌿",
    # === ENTERTAINMENT & MOVIES (Bengali) ===
    "সিনেমা কি": "সিনেমা বা চলচ্চিত্র হলো চলমান চিত্রের একটি সিরিজ যা গল্প বলে। 🎬",
    "অস্কার কি": "অস্কার হলো চলচ্চিত্রের বিশ্বের সবচেয়ে মর্যাদাপূর্ণ পুরস্কার। 🏆",
    "বলিউড কি": "বলিউড হলো ভারতের মুম্বাই ভিত্তিক হিন্দি চলচ্চিত্র শিল্প। 🎥",
    "ঢালিউড কি": "ঢালিউড হলো বাংলাদেশের ঢাকা ভিত্তিক চলচ্চিত্র শিল্প। 🇧🇩",
    "নেটফ্লিক্স কি": "নেটফ্লিক্স হলো একটি অনলাইন স্ট্রিমিং প্ল্যাটফর্ম যেখানে সিনেমা এবং সিরিজ দেখা যায়। 📺",
    "প্রথম সবাক চলচ্চিত্র": "বাংলায় প্রথম সবাক চলচ্চিত্র হলো 'জামাই ষষ্ঠী'। 🎬",

    # === ENTERTAINMENT & MOVIES (English) ===
    "what is cinema": "Cinema is a medium of storytelling using moving pictures and sound. 🎬",
    "what are oscars": "The Oscars are the most prestigious awards in the global film industry. 🏆",
    "hollywood": "Hollywood is the center of the American film industry, located in Los Angeles. 🇺🇸",
    "avengers": "The Avengers are a team of superheroes from Marvel Comics. 🦸‍♂️",
    "superman": "Superman is one of the most iconic superheroes, known for his strength and flight. 🦸‍♂️",

    # === NATURE & ANIMALS (Bengali) ===
    "বাঘ কেন সাহসী": "বাঘ হলো শিকারি প্রাণী এবং বনের রাজকীয়তা রক্ষা করে। 🐅",
    "হাতি কি খায়": "হাতি মূলত ঘাস, গাছের পাতা এবং ফল খেয়ে জীবনধারণ করে। 🐘",
    "পাখি কেন ওড়ে": "পাখিদের হালকা হাড় এবং শক্তিশালী ডানা তাদের উড়তে সাহায্য করে। 🐦",
    "মৌমাছি কি দেয়": "মৌমাছি আমাদের পুষ্টিকর মধু এবং মোম দেয়। 🐝",
    "গাছ কেন দরকার": "গাছ আমাদের অক্সিজেন দেয় এবং পরিবেশ ঠান্ডা রাখে। 🌳",

    # === NATURE & ANIMALS (English) ===
    "why do birds sing": "Birds sing to attract mates and defend their territory. 🐦",
    "how do fish breathe": "Fish use their gills to extract oxygen from the water. 🐟",
    "blue whale facts": "The blue whale is the largest animal ever known to have existed. 🐋",
    "importance of bees": "Bees are crucial for pollinating crops and maintaining biodiversity. 🐝",
    "amazon rainforest": "The Amazon is the world's largest tropical rainforest. 🌳",

    # === FAMOUS PERSONALITIES (Bengali) ===
    "রবীন্দ্রনাথ ঠাকুর কে": "রবীন্দ্রনাথ ঠাকুর হলেন বিশ্বকবি এবং গীতাঞ্জলির জন্য নোবেল বিজয়ী। ✍️",
    "কাজী নজরুল ইসলাম কে": "কাজী নজরুল ইসলাম হলেন বাংলাদেশের জাতীয় কবি এবং বিদ্রোহী কবি। 🇧🇩",
    "বঙ্গবন্ধু কে": "বঙ্গবন্ধু শেখ মুজিবুর রহমান হলেন বাংলাদেশের স্থপতি এবং জাতির পিতা। 🇧🇩",
    "আইনস্টাইন কে": "আলবার্ট আইনস্টাইন ছিলেন একজন বিশ্ববিখ্যাত তাত্ত্বিক পদার্থবিদ। 👨‍🔬",
    "নিউটন কে": "স্যার আইজ্যাক নিউটন ছিলেন একজন বিখ্যাত গণিতবিদ এবং পদার্থবিদ। 🍎",

    # === FAMOUS PERSONALITIES (English) ===
    "who was einstein": "Albert Einstein was a theoretical physicist who developed the theory of relativity. 👨‍🔬",
    "who was newton": "Isaac Newton was a scientist who formulated the laws of motion and universal gravitation. 🍎",
    "who is bill gates": "Bill Gates is the co-founder of Microsoft and a prominent philanthropist. 💻",
    "who is elon musk": "Elon Musk is the CEO of Tesla and SpaceX, known for his work in technology and space. 🚀",
    "steve jobs": "Steve Jobs was the co-founder of Apple and a pioneer of the personal computer revolution. 🍎",

    "big bang": "The Big Bang theory describes how the universe began about 13.8 billion years ago! 💥",
    "universe": "The universe is all of space, time, matter, and energy that exists! 🌌",
    "galaxy": "A galaxy is a massive system of stars, gas, dust, and dark matter bound by gravity! 🌠",
    "milky way": "The Milky Way is our home galaxy, containing 100-400 billion stars! 🌌",
    "solar system": "Our solar system has 8 planets orbiting the Sun, plus dwarf planets and other objects! 🪐",
    "sun": "The Sun is a star at the center of our solar system, converting hydrogen to helium! ☀️",
    "moon": "The Moon is Earth's only natural satellite, formed 4.5 billion years ago! 🌙",
    "earth": "Earth is the third planet from the Sun, the only known planet with life! 🌍",
    "mars": "Mars is the fourth planet, known as the Red Planet due to iron oxide on its surface! 🔴",
    # === SPACE & PLANETS (Bengali - Expanded) ===
    "সূর্য কত বড়": "সূর্য পৃথিবীর তুলনায় প্রায় ১৩ লক্ষ গুণ বড়। ☀️",
    "চাঁদ কত দূরে": "পৃথিবী থেকে চাঁদের গড় দূরত্ব প্রায় ৩ লক্ষ ৮৪ হাজার ৪০০ কিলোমিটার। 🌙",
    "সবচেয়ে বড় গ্রহ কোনটি": "সৌরজগতের সবচেয়ে বড় গ্রহ হলো বৃহস্পতি। 🪐",
    "সবচেয়ে ছোট গ্রহ কোনটি": "সৌরজগতের সবচেয়ে ছোট গ্রহ হলো বুধ। 🌑",
    "লাল গ্রহ কোনটি": "মঙ্গল গ্রহকে লাল গ্রহ বলা হয়। 🔴",
    "শনির বলয় কি দিয়ে তৈরি": "শনির বলয় মূলত বরফ এবং ধূলিকণা দিয়ে তৈরি। 🪐",
    "ইউরেনাস কেন নীল": "মিথেন গ্যাসের উপস্থিতির কারণে ইউরেনাস নীল দেখায়। 🔵",
    "নেপচুন কি": "নেপচুন হলো সূর্য থেকে সবচেয়ে দূরে অবস্থিত গ্রহ। 🌌",
    "প্লুটো কি গ্রহ": "প্লুটোকে এখন বামন গ্রহ (Dwarf Planet) হিসেবে গণ্য করা হয়। 🌑",
    "ধূমকেতু কি": "ধূমকেতু হলো বরফ, ধুলো এবং গ্যাসের তৈরি মহাজাগতিক বস্তু। ☄️",

    # === GEOGRAPHY (Bengali) ===
    "এশিয়ার সবচেয়ে বড় দেশ": "এশিয়ার আয়তনে সবচেয়ে বড় দেশ হলো চীন। 🇨🇳",
    "ইউরোপের সবচেয়ে বড় দেশ": "ইউরোপের সবচেয়ে বড় দেশ হলো রাশিয়া। 🇷🇺",
    "আফ্রিকার সবচেয়ে বড় দেশ": "আফ্রিকার আয়তনে সবচেয়ে বড় দেশ হলো আলজেরিয়া। 🇩🇿",
    "আমেরিকার সবচেয়ে বড় দেশ": "উত্তর আমেরিকার সবচেয়ে বড় দেশ হলো কানাডা। 🇨🇦",
    "অস্ট্রেলিয়া কি": "অস্ট্রেলিয়া একটি দেশ এবং একটি মহাদেশও। 🇦🇺",
    "সবচেয়ে গভীর মহাসাগর": "প্রশান্ত মহাসাগর হলো বিশ্বের সবচেয়ে গভীর মহাসাগর। 🌊",
    "সবচেয়ে বড় মরুভূমি": "বিশ্বের সবচেয়ে বড় উষ্ণ মরুভূমি হলো সাহারা। 🏜️",
    "মাউন্ট এভারেস্ট কোথায়": "মাউন্ট এভারেস্ট হিমালয় পর্বতমালায় নেপাল ও চীনের সীমান্তে অবস্থিত। 🏔️",
    "কক্সবাজার কেন বিখ্যাত": "কক্সবাজার বিশ্বের দীর্ঘতম অবিচ্ছিন্ন প্রাকৃতিক বালুকাময় সমুদ্র সৈকতের জন্য বিখ্যাত। 🏖️",
    "সুন্দরবন কোথায়": "সুন্দরবন বাংলাদেশ এবং ভারতের পশ্চিমবঙ্গ রাজ্যে অবস্থিত বিশ্বের বৃহত্তম ম্যানগ্রোভ বন। 🐅",

    # === HUMAN BODY (Bengali) ===
    "মানুষের হাড় কয়টি": "একজন প্রাপ্তবয়স্ক মানুষের শরীরে ২০৬টি হাড় থাকে। 🦴",
    "হৃদপিণ্ড কি করে": "হৃদপিণ্ড সারা শরীরে রক্ত পাম্প করে সরবরাহ করে। ❤️",
    "ফুসফুস কি কাজ করে": "ফুসফুস আমাদের শ্বাস নিতে এবং অক্সিজেন গ্রহণ করতে সাহায্য করে। 🫁",
    "মস্তিষ্ক কি": "মস্তিষ্ক হলো শরীরের নিয়ন্ত্রণ কেন্দ্র যা সব কাজ পরিচালনা করে। 🧠",
    "পাকস্থলী কি": "পাকস্থলী খাদ্য হজম করতে সাহায্য করে। 🥣",
    "রক্তের রং লাল কেন": "হিমোগ্লোবিনের উপস্থিতির কারণে রক্তের রং লাল হয়। 🩸",
    "মানুষের দাঁত কয়টি": "একজন প্রাপ্তবয়স্ক মানুষের সাধারণত ৩২টি দাঁত থাকে। 🦷",
    "চোখ কি কাজ করে": "চোখ আমাদের দেখতে সাহায্য করে। 👀",
    "কান কি কাজ করে": "কান আমাদের শুনতে এবং ভারসাম্য রক্ষা করতে সাহায্য করে। 👂",
    "ত্বক কি": "ত্বক হলো শরীরের বৃহত্তম অঙ্গ যা আমাদের রক্ষা করে। 🖐️",

    # === LIFE ADVICE (Bengali) ===
    "সফল হওয়ার উপায়": "কঠোর পরিশ্রম, ধৈর্য এবং সঠিক পরিকল্পনাই হলো সফল হওয়ার মূল মন্ত্র। ✨",
    "সুখী হওয়ার উপায়": "বর্তমানে বাঁচুন, ইতিবাচক চিন্তা করুন এবং অন্যের প্রতি দয়ালু হোন। 😊",
    "সময় নষ্ট করবেন না": "সময় একবার চলে গেলে আর ফিরে আসে না, তাই সময়ের সঠিক ব্যবহার করুন। 🕐",
    "শিক্ষার গুরুত্ব": "শিক্ষা হলো একটি জাতির মেরুদণ্ড এবং অন্ধকারের মধ্যে আলোর মতো। 📚",
    "স্বাস্থ্য রক্ষা": "সুষম খাবার খান এবং নিয়মিত ব্যায়াম করুন। 🍎",
    "পড়াশোনায় মন বসানোর উপায়": "একটি নির্দিষ্ট রুটিন তৈরি করুন এবং পড়ার সময় মোবাইল থেকে দূরে থাকুন। 📖",
    "মানসিক প্রশান্তি": "মেডিটেশন করুন এবং প্রকৃতির সাথে সময় কাটান। 🌿",
    "বিপদের বন্ধু": "বিপদের সময় যে পাশে থাকে সেই প্রকৃত বন্ধু। �",
    "কঠোর পরিশ্রম": "পরিশ্রম সৌভাগ্যের প্রসূতি। 🏆",
    "ধৈর্য ধরুন": "সবুরে মেওয়া ফলে। 🌈",

    "saturn": "Saturn is famous for its beautiful ring system made of ice and rock particles! 💍",
    "venus": "Venus is the hottest planet at 462°C due to extreme greenhouse effect! 🌡️",
    "mercury": "Mercury is the smallest planet and closest to the Sun, with extreme temperature variations! 🌡️",
    "neptune": "Neptune is the windiest planet, with winds reaching 2,100 km/h (1,300 mph)! 💨",
    "uranus": "Uranus rotates on its side at 98 degrees, making it unique in our solar system! 🪐",
    "pluto": "Pluto was reclassified as a dwarf planet in 2006, but it's still loved! ❄️",
    "asteroid": "Asteroids are rocky objects orbiting the Sun, mostly found in the asteroid belt! 🪨",
    "comet": "Comets are icy bodies that develop tails when near the Sun due to solar radiation! ☄️",
    "meteor": "A meteor (shooting star) is a small body entering Earth's atmosphere and burning up! ⭐",
    # === HISTORY (Bengali) ===
    "বাংলাদেশের মুক্তিযুদ্ধ": "১৯৭১ সালে ৯ মাস রক্তক্ষয়ী যুদ্ধের মাধ্যমে বাংলাদেশ স্বাধীন হয়। 🇧🇩",
    "ভাষার লড়াই": "১৯৫২ সালের ২১শে ফেব্রুয়ারি বাংলা ভাষার জন্য প্রাণ দিয়েছিলেন সালাম, বরকত, রফিক, জব্বারসহ অনেকে। 🇧🇩",
    "পলাশীর যুদ্ধ": "১৭৫৭ সালের ২৩শে জুন পলাশীর যুদ্ধে বাংলার শেষ স্বাধীন নবাব সিরাজউদ্দৌলা পরাজিত হন। ⚔️",
    "প্রথম বিশ্বযুদ্ধ": "১৯১৪ থেকে ১৯১৮ সাল পর্যন্ত প্রথম বিশ্বযুদ্ধ স্থায়ী হয়েছিল। ⚔️",
    "দ্বিতীয় বিশ্বযুদ্ধ": "১৯৩৯ থেকে ১৯৪৫ সাল পর্যন্ত দ্বিতীয় বিশ্বযুদ্ধ হয়েছিল। 🌍",

    # === HISTORY (English) ===
    "world war 1": "World War I lasted from 1914 to 1918. ⚔️",
    "world war 2": "World War II lasted from 1939 to 1945. 🌍",
    "industrial revolution": "The Industrial Revolution began in the 18th century in Great Britain. 🏭",
    "french revolution": "The French Revolution began in 1789 and overthrew the absolute monarchy. 🇫🇷",
    "ancient egypt": "Ancient Egypt is famous for its pyramids and pharaohs along the Nile River. 🏛️",

    # === SCIENCE & PHYSICS (Bengali) ===
    "মহাকর্ষ কি": "মহাকর্ষ হলো ভরের কারণে বস্তুর মধ্যে যে আকর্ষণ বল কাজ করে। 🌍",
    "আপেক্ষিকতা তত্ত্ব": "আইনস্টাইনের আপেক্ষিকতা তত্ত্ব স্থান এবং সময়ের সম্পর্ক ব্যাখ্যা করে। 👨‍🔬",
    "আলোকবর্ষ কি": "আলো এক বছরে যে দূরত্ব অতিক্রম করে তাকে আলোকবর্ষ বলে। ✨",
    "পরমাণু কি": "পরমাণু হলো পদার্থের ক্ষুদ্রতম কণা। ⚛️",
    "ডিএনএ কি": "ডিএনএ হলো জীবের বংশগতির বাহক। 🧬",

    # === SCIENCE & PHYSICS (English) ===
    "quantum physics": "Quantum physics deals with the behavior of matter and energy at the scale of atoms and subatomic particles. ⚛️",
    "theory of relativity": "Einstein's theory of relativity explains the relationship between space, time, and gravity. 👨‍🔬",
    "speed of light value": "The speed of light is exactly 299,792,458 meters per second. ⚡",
    "what is energy": "Energy is the capacity to do work. ⚡",
    "what is matter": "Matter is anything that has mass and takes up space. 🪨",

    # === COMPUTER SCIENCE (Bengali) ===
    "সফটওয়্যার কি": "কম্পিউটারকে নির্দেশ দেওয়ার জন্য প্রোগ্রামের সেটকে সফটওয়্যার বলে। 💻",
    "হার্ডওয়্যার কি": "কম্পিউটারের বাহ্যিক যন্ত্রাংশগুলোকে হার্ডওয়্যার বলে। 🖥️",
    "বাইনারি সংখ্যা": "বাইনারি হলো ০ এবং ১ ভিত্তিক সংখ্যা পদ্ধতি। 🔢",
    "প্রোগ্রামিং কি": "কম্পিউটারকে কোনো কাজ করার নির্দেশ দেওয়ার পদ্ধতিই হলো প্রোগ্রামিং। 🐍",
    "অপারেটিং সিস্টেম": "এটি একটি সফটওয়্যার যা হার্ডওয়্যার ও ইউজারের মধ্যে সমন্বয় করে। ⚙️",

    # === COMPUTER SCIENCE (English) ===
    "what is a database": "A database is an organized collection of structured information or data. 📊",
    "cloud computing": "Cloud computing is the delivery of computing services over the internet. ☁️",
    "cyber security": "Cyber security is the practice of protecting systems and networks from digital attacks. 🛡️",
    "machine learning": "Machine learning is a subset of AI that focuses on building systems that learn from data. 🤖",
    "blockchain": "A blockchain is a decentralized, distributed ledger that records transactions across many computers. ⛓️",

    "supernova": "A supernova is a powerful explosion marking the end of a massive star's life! 💥",
    "neutron star": "Neutron stars are incredibly dense - a teaspoon weighs about 6 billion tons! ⚛️",
    "white dwarf": "White dwarfs are the dense remnants of stars that have exhausted their nuclear fuel! ⭐",
    "red giant": "Red giants are evolved stars that have exhausted hydrogen in their cores and expanded! 🔴",
    "constellation": "Constellations are patterns of stars forming recognizable shapes, used for navigation! ⭐",
    "aurora": "Auroras (Northern/Southern Lights) are caused by charged particles from the Sun hitting Earth's atmosphere! 🌌",
    "rainbow": "Rainbows form when sunlight is refracted, reflected, and dispersed by water droplets! 🌈",
    "lightning": "Lightning is a sudden electrostatic discharge during thunderstorms, hotter than the Sun's surface! ⚡",
    "thunder": "Thunder is the sound caused by lightning rapidly heating air and creating shock waves! 🌩️",
    # === HEALTH & WELLNESS (Bengali) ===
    "সুস্থ থাকার উপায়": "সুষম খাবার খান, নিয়মিত ব্যায়াম করুন এবং পর্যাপ্ত ঘুমান। 🥗",
    "ব্যায়ামের উপকারিতা": "ব্যায়াম হৃদরোগের ঝুঁকি কমায় এবং মানসিক স্বাস্থ্য উন্নত করে। 🏃",
    "বেশি পানি খাওয়ার উপকারিতা": "পানি শরীর থেকে টক্সিন বের করে দেয় এবং ত্বক ভালো রাখে। 💧",
    "ভিটামিন সি এর উৎস": "লেবু, কমলা, এবং আমলকী ভিটামিন সি এর চমৎকার উৎস। 🍋",
    "মানসিক চাপ কমানোর উপায়": "বই পড়ুন, প্রিয়জনের সাথে সময় কাটান এবং পর্যাপ্ত বিশ্রাম নিন। 🧘",

    # === HEALTH & WELLNESS (English) ===
    "how to stay fit": "Maintain a balanced diet, exercise regularly, and stay hydrated! 🏃",
    "benefits of drinking water": "Drinking water helps regulate body temperature and aids digestion! 💧",
    "healthy breakfast ideas": "Oats, eggs, yogurt, and fresh fruits are great breakfast choices! 🍳",
    "importance of sleep": "Sleep is crucial for physical health and brain function! 😴",
    "vitamin d sources": "Sunlight is the best source of Vitamin D, along with fatty fish and eggs! ☀️",

    # === SCIENCE & MATH (Bengali - Expanded) ===
    "পাই এর মান": "পাই (Pi) এর মান সাধারণত ৩.১৪১৬ হিসেবে ধরা হয়। 🔢",
    "অভিকর্ষজ ত্বরণ": "পৃথিবীতে অভিকর্ষজ ত্বরণ (g) এর গড় মান ৯.৮ মি/সে²। 🌍",
    "আলোর বেগ কত": "আলোর বেগ প্রতি সেকেন্ডে প্রায় ৩ লক্ষ কিলোমিটার। ⚡",
    "মৌলিক সংখ্যা কি": "যে সংখ্যা ১ এবং ঐ সংখ্যা ছাড়া অন্য কিছু দিয়ে বিভাজ্য নয় তাকে মৌলিক সংখ্যা বলে। 🔢",
    "পানির স্ফুটনাঙ্ক": "স্বাভাবিক চাপে পানির স্ফুটনাঙ্ক ১০০ ডিগ্রি সেলসিয়াস। 🌡️",

    # === SCIENCE & MATH (English - Expanded) ===
    "value of pi": "The mathematical constant Pi is approximately 3.14159. 🔢",
    "boiling point of water": "Water boils at 100 degrees Celsius or 212 degrees Fahrenheit. 🌡️",
    "speed of light value": "The speed of light is 299,792,458 meters per second. ⚡",
    "what is a prime number": "A prime number is a number greater than 1 with no divisors other than 1 and itself. 🔢",
    "newton's first law": "An object at rest stays at rest unless acted upon by an external force. 🍎",

    # === GEOGRAPHY (Bengali - Expanded) ===
    "সবচেয়ে বড় মহাসাগর কোনটি": "প্রশান্ত মহাসাগর বিশ্বের বৃহত্তম এবং গভীরতম মহাসাগর। 🌊",
    "বাংলাদেশের দীর্ঘতম নদী": "মেঘনা হলো বাংলাদেশের অন্যতম দীর্ঘতম নদী। 🌊",
    "সবচেয়ে বড় মহাদেশ": "এশিয়া বিশ্বের বৃহত্তম মহাদেশ। 🌍",
    "সবচেয়ে ছোট মহাদেশ": "অস্ট্রেলিয়া বিশ্বের সবচেয়ে ছোট মহাদেশ। 🌏",
    "সাতটি মহাদেশের নাম": "এশিয়া, আফ্রিকা, ইউরোপ, উত্তর আমেরিকা, দক্ষিণ আমেরিকা, অ্যান্টার্কটিকা এবং অস্ট্রেলিয়া। 🌍",

    # === GEOGRAPHY (English - Expanded) ===
    "deepest ocean": "The Pacific Ocean is the deepest ocean in the world. 🌊",
    "highest mountain peak": "Mount Everest is the highest peak above sea level. 🏔️",
    "longest river in world": "The Nile is traditionally considered the longest river in the world. 🌊",
    "largest country by area": "Russia is the largest country by land area. 🇷🇺",
    "smallest country by area": "Vatican City is the smallest country in the world. 🇻�",

    "hurricane": "Hurricanes are massive tropical storms with winds over 74 mph (119 km/h)! 🌀",
    "earthquake": "Earthquakes are caused by sudden movements of tectonic plates in Earth's crust! 🌍",
    "volcano": "Volcanoes erupt when magma from Earth's mantle reaches the surface! 🌋",
    "tsunami": "Tsunamis are giant ocean waves caused by underwater earthquakes or volcanic eruptions! 🌊",
    "tides": "Tides are caused by the gravitational pull of the Moon and Sun on Earth's oceans! 🌊",
    "seasons": "Seasons are caused by Earth's 23.5° tilt as it orbits the Sun! 🍂",
    "climate": "Climate is the long-term pattern of weather in a particular area! 🌤️",
    "weather": "Weather is the short-term atmospheric conditions like temperature, humidity, and precipitation! 🌦️",
    "clouds": "Clouds form when water vapor condenses into tiny droplets or ice crystals in the atmosphere! ☁️",
    # === BUSINESS & ECONOMY (Bengali) ===
    "টাকা কি": "টাকা হলো বিনিময়ের মাধ্যম যা পণ্য ও সেবার মূল্য পরিশোধে ব্যবহৃত হয়। 💰",
    "ব্যাংক কি": "ব্যাংক হলো একটি আর্থিক প্রতিষ্ঠান যা আমানত গ্রহণ করে এবং ঋণ প্রদান করে। 🏦",
    "শেয়ার বাজার": "শেয়ার বাজার হলো এমন একটি জায়গা যেখানে কোম্পানির শেয়ার কেনাবেচা করা হয়। 📈",
    "জিডিপি কি": "জিডিপি (GDP) হলো একটি দেশের অভ্যন্তরে উৎপাদিত মোট পণ্য ও সেবার বাজার মূল্য। 📊",
    "মুদ্রাস্ফীতি": "মুদ্রাস্ফীতি হলো সময়ের সাথে সাথে পণ্য ও সেবার দাম বৃদ্ধি পাওয়া। 💸",

    # === BUSINESS & ECONOMY (English) ===
    "what is money": "Money is a medium of exchange used to pay for goods, services, and debts. 💰",
    "how banks work": "Banks accept deposits from customers and use that money to provide loans to others. 🏦",
    "stock market basics": "The stock market is where investors buy and sell ownership in public companies. 📈",
    "what is inflation": "Inflation is the rate at which the general level of prices for goods and services is rising. 💸",
    "cryptocurrency": "Cryptocurrency is a digital or virtual currency secured by cryptography, usually based on blockchain. ₿",

    # === SPORTS & ATHLETES (Bengali - Expanded) ===
    "বাংলাদেশ ক্রিকেট বোর্ড": "বিসিবি (BCB) হলো বাংলাদেশের ক্রিকেটের নিয়ন্ত্রণকারী সংস্থা। 🏏",
    "প্রথম টেস্ট জয়": "বাংলাদেশ তাদের প্রথম টেস্ট জয় পায় ২০০৫ সালে জিম্বাবুয়ের বিপক্ষে। 🏏",
    "সাকিব আল হাসান": "সাকিব আল হাসান বিশ্বের অন্যতম সেরা অলরাউন্ডার এবং বাংলাদেশের গর্ব। 🇧🇩",
    "তামিম ইকবাল": "তামিম ইকবাল বাংলাদেশের অন্যতম সফল ওপেনিং ব্যাটসম্যান। 🏏",
    "মুশফিকুর রহিম": "মুশফিকুর রহিম বাংলাদেশের একজন নির্ভরযোগ্য ব্যাটসম্যান এবং উইকেটরক্ষক। 🏏",

    # === SPORTS & ATHLETES (English - Expanded) ===
    "who is kohl": "Virat Kohli is an Indian international cricketer and one of the best batsmen in the world. 🏏",
    "lebron james": "LeBron James is an American professional basketball player in the NBA. 🏀",
    "serena williams": "Serena Williams is an American former professional tennis player, widely considered one of the greatest. 🎾",
    "tiger woods": "Tiger Woods is an American professional golfer, one of the most successful of all time. ⛳",
    "roger federer": "Roger Federer is a Swiss former professional tennis player known for his elegance on court. 🎾",

    # === DAILY LIFE HACKS (Bengali) ===
    "পড়া মনে রাখার উপায়": "পড়ার পর তা লিখে ফেলুন এবং পর্যাপ্ত ঘুমান। 📝",
    "দ্রুত ঘুম আসার উপায়": "শোয়ার আগে হালকা গরম দুধ খেতে পারেন এবং ফোন থেকে দূরে থাকুন। 😴",
    "ওজন কমানোর উপায়": "চিনি ও ভাজাপোড়া খাবার এড়িয়ে চলুন এবং নিয়মিত হাঁটুন। 🏃",
    "রান্না করার টিপস": "রান্নায় টাটকা মশলা ব্যবহার করলে স্বাদ ও ঘ্রাণ ভালো হয়। 🥘",
    "গাছের যত্ন": "গাছে নিয়মিত পানি দিন এবং পর্যাপ্ত সূর্যালোক নিশ্চিত করুন। 🪴",

    # === DAILY LIFE HACKS (English) ===
    "how to wake up early": "Put your alarm across the room and go to bed at a consistent time. ⏰",
    "cleaning hacks": "Baking soda and vinegar are great for cleaning many household surfaces. ✨",
    "study productivity": "Use the Pomodoro technique: 25 minutes of study followed by a 5-minute break. ⏳",
    "staying hydrated": "Carry a reusable water bottle with you throughout the day. 💧",
    "improving mood": "Listening to upbeat music or taking a short walk can quickly boost your mood. �",

    "snow": "Snow forms when water vapor freezes into ice crystals in cold clouds! ❄️",
    "hail": "Hail is ice pellets formed when thunderstorm updrafts repeatedly lift and freeze water droplets! 🧊",
    "fog": "Fog is a cloud at ground level, formed when air near the surface cools to its dew point! 🌫️",
    "wind": "Wind is air moving from high to low pressure areas, caused by uneven solar heating! 💨",
    "humidity": "Humidity is the amount of water vapor in the air! 💧",
    "barometer": "A barometer measures atmospheric pressure to help predict weather changes! 📊",
    "temperature": "Temperature measures the average kinetic energy of particles in a substance! 🌡️",
    "heat": "Heat is energy transferred between systems due to temperature differences! 🔥",
    "energy": "Energy is the capacity to do work, existing in forms like kinetic, potential, thermal, and more! ⚡",
    # === BANGLADESH & CULTURE (Bengali) ===
    "বাংলাদেশের মুক্তিযুদ্ধ": "১৯৭১ সালে ৯ মাস রক্তক্ষয়ী যুদ্ধের মাধ্যমে ১৬ই ডিসেম্বর বাংলাদেশ স্বাধীন হয়। 🇧🇩",
    "বঙ্গবন্ধু কে": "শেখ মুজিবুর রহমান হলেন বাংলাদেশের স্থপতি এবং জাতির পিতা। 🇧🇩",
    "জাতীয় স্মৃতিসৌধ": "এটি সাভারে অবস্থিত এবং বাংলাদেশের স্বাধীনতা যুদ্ধের শহীদদের স্মরণে নির্মিত। 🏛️",
    "শহীদ মিনার": "ভাষা আন্দোলনের শহীদদের স্মরণে এটি ঢাকা মেডিকেল কলেজের পাশে অবস্থিত। 🇧🇩",
    "জাতীয় কবি কে": "কাজী নজরুল ইসলাম হলেন বাংলাদেশের জাতীয় কবি। ✍️",
    "রবীন্দ্রনাথ ঠাকুর": "বিশ্বকবি রবীন্দ্রনাথ ঠাকুর বাংলা সাহিত্যের অন্যতম প্রধান ব্যক্তিত্ব এবং আমাদের জাতীয় সংগীতের রচয়িতা। ✍️",
    "পহেলা বৈশাখ": "এটি বাংলা নববর্ষের প্রথম দিন, যা অত্যন্ত জাঁকজমকভাবে পালিত হয়। 🎊",
    "লালন শাহ": "লালন শাহ ছিলেন একজন প্রখ্যাত বাউল সাধক এবং সমাজ সংস্কারক। 🎵",
    "সুন্দরবন": "সুন্দরবন বিশ্বের বৃহত্তম ম্যানগ্রোভ বন এবং এটি রয়েল বেঙ্গল টাইগারের আবাসস্থল। 🐅",
    "কক্সবাজার": "এটি বিশ্বের দীর্ঘতম প্রাকৃতিক সমুদ্র সৈকত। 🏖️",

    # === BANGLADESH & CULTURE (English) ===
    "liberation war of bangladesh": "Bangladesh gained independence in 1971 after a 9-month-long liberation war. 🇧🇩",
    "who is bangabandhu": "Sheikh Mujibur Rahman is the founding father of Bangladesh. 🇧🇩",
    "national anthem of bangladesh": "The national anthem is 'Amar Sonar Bangla', written by Rabindranath Tagore. 🎵",
    "bangladesh independence day": "Independence Day is celebrated on March 26th. 🇧🇩",
    "victory day bangladesh": "Victory Day is celebrated on December 16th. 🇧🇩",
    "language movement day": "February 21st is International Mother Language Day, originating from the 1952 Language Movement. 🇧🇩",
    "traditional bangladeshi food": "Rice and fish (Panta Ilish) are staples, along with various pithas and sweets. 🍛",
    "national animal of bangladesh": "The Royal Bengal Tiger is the national animal of Bangladesh. 🐅",
    "national bird of bangladesh": "The Oriental Magpie-Robin (Doel) is the national bird. 🐦",
    "longest beach in world": "Cox's Bazar in Bangladesh is the world's longest natural sandy beach. 🏖️",

    # === DAILY LIFE & PRODUCTIVITY (Bengali) ===
    "পড়া মনে রাখার কৌশল": "পড়ার সময় ছবি আঁকুন, নোট নিন এবং পর্যাপ্ত ঘুমান। 📝",
    "সকালে তাড়াতাড়ি ওঠার উপায়": "অ্যালার্ম ঘড়ি দূরে রাখুন এবং নির্দিষ্ট সময়ে ঘুমাতে যান। ⏰",
    "কিভাবে স্মার্ট হওয়া যায়": "বেশি বই পড়ুন, নতুন কিছু শেখার চেষ্টা করুন এবং অন্যের কথা মনোযোগ দিয়ে শুনুন। 🧠",
    "ভালো ছাত্র হওয়ার উপায়": "ক্লাসে নিয়মিত হোন, পড়া জমিয়ে রাখবেন না এবং নিয়মিত রিভিশন দিন। 📚",
    "কিভাবে আত্মবিশ্বাস বাড়ানো যায়": "নিজের ছোট ছোট অর্জনকে গুরুত্ব দিন এবং ইতিবাচক চিন্তা করুন। ✨",

    # === DAILY LIFE & PRODUCTIVITY (English) ===
    "how to improve focus": "Minimize distractions, use deep work blocks, and take regular breaks. 🧘",
    "importance of reading": "Reading expands your knowledge, improves vocabulary, and reduces stress. 📖",
    "learning a new language": "Practice daily, watch movies in that language, and talk to native speakers. 🗣️",
    "effective time management": "Use a planner, prioritize tasks using the Eisenhower Matrix, and avoid multitasking. ⏳",
    "developing a habit": "Start small, be consistent for at least 21 days, and track your progress. 📈",

    "magnetism": "Magnetism is a force produced by moving electric charges attracting ferromagnetic materials! 🧲",
    "radiation": "Radiation is energy traveling through space or matter as waves or particles! ☢️",
    "radioactivity": "Radioactivity is the spontaneous decay of unstable atomic nuclei, emitting radiation! ☢️",
    "nuclear fission": "Nuclear fission splits atomic nuclei, releasing energy used in power plants and bombs! ⚛️",
    "nuclear fusion": "Nuclear fusion combines light nuclei, like in the Sun - the holy grail of clean energy! ☀️",
    "quantum mechanics": "Quantum mechanics describes physics at the atomic and subatomic scale! ⚛️",
    "relativity": "Einstein's theory of relativity describes gravity as the curvature of spacetime! 🌌",
    "pi": "Pi (π) is the ratio of a circle's circumference to its diameter, approximately 3.14159...! π",
    "fibonacci": "The Fibonacci sequence (1,1,2,3,5,8...) appears in natural patterns like shells and flowers! 🐚",
    # === TRAVEL & TOURISM (Bengali) ===
    "সাজেক ভ্যালি": "সাজেক ভ্যালি রাঙ্গামাটি জেলায় অবস্থিত বাংলাদেশের একটি জনপ্রিয় পর্যটন কেন্দ্র যা মেঘের দেশের জন্য পরিচিত। ☁️",
    "সেন্ট মার্টিন": "সেন্ট মার্টিন বাংলাদেশের একমাত্র প্রবাল দ্বীপ যা কক্সবাজারের কাছে অবস্থিত। 🏝️",
    "জাফলং": "জাফলং সিলেটের একটি মনোরম পর্যটন কেন্দ্র যা পাহাড় ও ঝরনার জন্য বিখ্যাত। 🏔️",
    "রাতারগুল": "জাফলংয়ের কাছে অবস্থিত রাতারগুল বাংলাদেশের একমাত্র মিঠাপানির জলাবন বা সোয়াম্প ফরেস্ট। 🛶",
    "পদ্মা সেতু": "পদ্মা সেতু বাংলাদেশের দীর্ঘতম বহুমুখী সেতু যা দেশের দক্ষিণ-পশ্চিমাঞ্চলকে যুক্ত করেছে। 🌉",

    # === TRAVEL & TOURISM (English) ===
    "sajek valley": "Sajek Valley is a beautiful hill station in Rangamati known for its stunning views of clouds. ☁️",
    "st martin island": "St. Martin's is the only coral island in Bangladesh, located in the Bay of Bengal. 🏝️",
    "jaflong": "Jaflong is a scenic spot in Sylhet known for its tea gardens and stone collection. 🏔️",
    "padma bridge": "The Padma Bridge is the longest multi-purpose bridge in Bangladesh, a symbol of pride. 🌉",
    "kuakata": "Kuakata is a beach in southern Bangladesh from where you can see both sunrise and sunset. 🌅",

    # === FAMOUS AUTHORS (Bengali) ===
    "হুমায়ূন আহমেদ": "হুমায়ূন আহমেদ ছিলেন বাংলাদেশের একজন অত্যন্ত জনপ্রিয় লেখক, নাট্যকার ও চলচ্চিত্র নির্মাতা। ✍️",
    "শরত্চন্দ্র চট্টোপাধ্যায়": "শরত্চন্দ্র চট্টোপাধ্যায় ছিলেন একজন জনপ্রিয় বাঙালি কথাসাহিত্যিক। ✍️",
    "বঙ্কিমচন্দ্র চট্টোপাধ্যায়": "বঙ্কিমচন্দ্র চট্টোপাধ্যায় ছিলেন প্রথম সার্থক বাঙালি ঔপন্যাসিক। ✍️",
    "জসীমউদ্দীন": "জসীমউদ্দীন ছিলেন পল্লীকবি হিসেবে পরিচিত একজন বিখ্যাত বাংলাদেশি কবি। 🌾",
    "জীবনানন্দ দাশ": "জীবনানন্দ দাশ ছিলেন রূপসী বাংলার কবি হিসেবে পরিচিত প্রখ্যাত কবি। ✍️",

    # === FAMOUS AUTHORS (English) ===
    "william shakespeare": "William Shakespeare was a famous English playwright and poet, known for Romeo and Juliet. 🎭",
    "charles dickens": "Charles Dickens was a great Victorian novelist known for A Tale of Two Cities. ✍️",
    "mark twain": "Mark Twain was a famous American writer, known for The Adventures of Tom Sawyer. ✍️",
    "j.k. rowling": "J.K. Rowling is the famous author of the Harry Potter fantasy series. 🪄",
    "ernest hemingway": "Ernest Hemingway was an influential American novelist and Nobel Prize winner. ✍️",

    # === MOTIVATIONAL QUOTES (Bengali) ===
    "অনুপ্রেরণামূলক কথা": "বিফলতা মানেই শেষ নয়, বরং নতুন করে শুরু করার সুযোগ। ✨",
    "পরিশ্রমের ফল": "সাফল্যের কোনো গোপন পথ নেই, এটি কেবল কঠোর পরিশ্রমের ফল। 🏆",
    "স্বপ্ন নিয়ে উক্তি": "স্বপ্ন সেটা নয় যা তুমি ঘুমিয়ে দেখো, স্বপ্ন সেটাই যা তোমাকে ঘুমাতে দেয় না। ✨",
    "হতাশা কাটানোর উপায়": "নিজেকে বিশ্বাস করুন, আপনি আপনার ধারণার চেয়েও বেশি শক্তিশালী। 🌈",
    "ধৈর্য নিয়ে কথা": "ধৈর্য ধরুন, ভালো সময় আসতে একটু সময় লাগে। ⌛",

    # === MOTIVATIONAL QUOTES (English) ===
    "motivational quote": "Believe you can and you're halfway there. ✨",
    "hard work quote": "Hard work beats talent when talent doesn't work hard. 🏆",
    "failure quote": "Failure is not the opposite of success; it's part of success. 🚀",
    "happiness quote": "Happiness depends upon ourselves. �",
    "persistence quote": "It always seems impossible until it's done. 🌈",

    "prime number": "Prime numbers are only divisible by 1 and themselves (2, 3, 5, 7, 11...)! 🔢",
    
    # === GAMING (100+ entries) ===
    "minecraft": "Minecraft is a sandbox game where players build and explore blocky worlds! ⛏️",
    "fortnite": "Fortnite is a battle royale game with 100 players fighting to be the last one standing! 🎮",
    "roblox": "Roblox is a platform where users create and play games made by other users! 🎮",
    "valorant": "Valorant is a tactical first-person shooter by Riot Games with unique agent abilities! 🎯",
    "csgo": "CS:GO is a competitive first-person shooter with terrorists vs counter-terrorists! 🔫",
    "call of duty": "Call of Duty is a military FPS franchise with intense multiplayer action! 🎖️",
    # === BANGLA RIDDLES (ধাঁধা) ===
    "কাঁচায় সবুজ পাকলে লাল": "মরিচ! 🌶️",
    "জল খেলে মরে যায়": "তৃষ্ণা! 💧",
    "পা নেই কিন্তু চলে": "চিঠি! ✉️",
    "তিন অক্ষরের নাম তার": "কলম! 🖋️",
    "আছে পা কিন্তু হাঁটে না": "টেবিল! 🪑",
    "মাথার উপর পা": "ছাতা! ⛱️",

    # === ENGLISH RIDDLES ===
    "what has keys but no locks": "A piano! 🎹",
    "what has a heart that doesn't beat": "An artichoke! 🥗",
    "what travels around the world but stays in a corner": "A stamp! ✉️",
    "what has one eye but can't see": "A needle! 🪡",
    "what gets wetter as it dries": "A towel! 🧼",

    # === BANGLA PROVERBS (প্রবাদ বাক্য) ===
    "সবুরে মেওয়া ফলে": "ধৈর্য ধরলে সুফল পাওয়া যায়। ⌛",
    "নাই মামার চেয়ে কানা মামা ভালো": "একেবারে না পাওয়ার চেয়ে অল্প পাওয়াও ভালো। 😊",
    "অল্প বিদ্যা ভয়ংকরী": "অল্প জ্ঞান অনেক সময় বিপদের কারণ হয়। 📚",
    "সময়ের এক ফোঁড় অসময়ের দশ ফোঁড়": "সময়মতো কাজ না করলে পরে অনেক বেশি কষ্ট করতে হয়। 🕐",

    # === ENGLISH PROVERBS ===
    "honesty is the best policy": "Being truthful is always the right choice. ✨",
    "practice makes perfect": "Doing something repeatedly helps you master it. 🎯",
    "time is money": "Time is a valuable resource, use it wisely. 💰",
    "better late than never": "It is better to finish something late than not at all. ✅",

    # === BANGLA DAILY CONVERSATION ===
    "খবর কি বন্ধু": "সব ভালো! তোর কি খবর? 😊",
    "মাথা ব্যাথা করছে": "একটু বিশ্রাম নে বা চা খা, ঠিক হয়ে যাবে। ☕",
    "আজকের আবহাওয়া": "বাইরে তাকিয়ে দেখ অথবা গুগল সার্চ দিয়ে জেনে নে বন্ধু! 🌤️",
    "পড়াশোনা কেমন চলছে": "আশা করি ভালো চলছে, মন দিয়ে পড়! 📖",
    "খেলাধুলা করিস": "হ্যাঁ, শরীর ঠিক রাখতে খেলাধুলা দরকার। ⚽",

    # === ENGLISH DAILY CONVERSATION ===
    "how's your day": "My day is going great! How about yours? 😊",
    "i'm bored": "Why don't you try learning something new or playing a game? 🎮",
    "what should i watch": "Depends on your taste! Maybe a sci-fi movie? 🍿",
    "hungry again": "Go grab a healthy snack! 🍎",
    "need a break": "Take 10 minutes to stretch and breathe. �",

    "apex legends": "Apex Legends is a battle royale with hero characters and unique abilities! 🦸",
    "gta": "GTA (Grand Theft Auto) is an open-world action-adventure series by Rockstar! 🚗",
    "gta 5": "GTA V is one of the best-selling games ever, featuring three playable protagonists! 🌴",
    "the witcher": "The Witcher 3 is an acclaimed RPG following monster hunter Geralt of Rivia! ⚔️",
    "skyrim": "Skyrim is an epic fantasy RPG where you fight dragons and explore a vast world! 🐉",
    "elden ring": "Elden Ring is an open-world soulslike game by FromSoftware and George R.R. Martin! 🗡️",
    "god of war": "God of War follows Kratos, a Spartan warrior who battles gods and monsters! ⚔️",
    "spider man": "Spider-Man games let you swing through New York as everyone's favorite web-slinger! 🕷️",
    "assassin creed": "Assassin's Creed features historical settings and stealthy assassin gameplay! 🗡️",
    "red dead redemption": "RDR2 is an epic western open-world game with incredible storytelling! 🤠",
    "fifa": "FIFA/EA FC is the world's most popular soccer simulation! ⚽",
    "nba 2k": "NBA 2K is the dominant basketball simulation game! 🏀",
    "rocket league": "Rocket League is soccer played with rocket-powered cars! 🚗⚽",
    "league of legends": "League of Legends is the world's most popular MOBA game! 🏆",
    "dota 2": "Dota 2 is a complex MOBA with a massive competitive scene! ⚔️",
    "overwatch": "Overwatch is a team-based shooter with unique heroes and abilities! 🦸",
    "minecraft": "Minecraft is the best-selling game ever with infinite creative possibilities! ⛏️",
    "pokemon": "Pokemon games involve catching and training creatures to battle! ⚡",
    "zelda": "The Legend of Zelda follows Link saving Hyrule from Ganon! 🗡️",
    "mario": "Super Mario is Nintendo's iconic platforming franchise! 🍄",
    "mario kart": "Mario Kart is a fun racing game with Nintendo characters! 🏎️",
    "super smash bros": "Super Smash Bros. is the ultimate crossover fighting game! 👊",
    "among us": "Among Us is a social deduction game about finding the impostor! 🔪",
    "fall guys": "Fall Guys is a battle royale with colorful bean characters and obstacle courses! 🫘",
    "valorant": "Valorant combines precise gunplay with unique agent abilities! 🎯",
    "genshin impact": "Genshin Impact is a free-to-play action RPG with gacha mechanics! 🌟",
    "honkai star rail": "HSR is a turn-based RPG from the makers of Genshin Impact! 🚂",
    "fortnite": "Fortnite's battle royale is free and features building mechanics! 🏗️",
    "warzone": "Call of Duty: Warzone is a free-to-play battle royale! 🔫",
    "apex": "Apex Legends features unique Legends with special abilities! 🦸",
    "rainbow six siege": "R6 Siege is a tactical shooter focused on destruction and gadgets! 💥",
    "destiny 2": "Destiny 2 is a looter-shooter with sci-fi setting and raids! 🌌",
    "warframe": "Warframe is a free-to-play cooperative shooter with fast-paced ninja combat! 🥷",
    "terraria": "Terraria is a 2D sandbox adventure often called '2D Minecraft'! ⛏️",
    "stardew valley": "Stardew Valley is a farming sim where you inherit your grandfather's farm! 🌾",
    "hades": "Hades is a roguelike where you escape Greek Hell with incredible narrative! 🔥",
    "hollow knight": "Hollow Knight is a beautiful metroidvania about a bug exploring a ruined kingdom! 🐛",
    "celeste": "Celeste is a challenging platformer about climbing a mountain and dealing with anxiety! 🏔️",
    "undertale": "Undertale is an RPG where you can spare every enemy you meet! 💙",
    "deltarune": "Deltarune is Toby Fox's follow-up to Undertale! 🃏",
    "portal": "Portal is a puzzle game using a portal gun to navigate test chambers! 🌀",
    "portal 2": "Portal 2 added co-op and one of gaming's best narratives! 🌀",
    "half life": "Half-Life revolutionized storytelling in FPS games! 🧪",
    "half life 2": "Half-Life 2 introduced the Source engine and physics gameplay! 🧪",
    "team fortress 2": "TF2 is a classic team-based shooter with distinct classes! 🔫",
    "left 4 dead 2": "L4D2 is the ultimate cooperative zombie shooter! 🧟",
    "garrys mod": "Garry's Mod is a physics sandbox with no objectives - just creativity! 🛠️",
    "rust": "Rust is a brutal survival game where players are the real threat! ☢️",
    "ark": "ARK: Survival Evolved has you tame dinosaurs on a mysterious island! 🦕",
    "dayz": "DayZ is a hardcore zombie survival mod turned standalone! 🧟",
    "pubg mobile": "PUBG Mobile brings the battle royale to phones! 📱",
    "cod mobile": "Call of Duty: Mobile has multiple modes including battle royale! 🔫",
    "mobile legends": "Mobile Legends is a popular mobile MOBA! 📱",
    "free fire": "Free Fire is a lightweight mobile battle royale! 🔥",
    "roblox": "Roblox has millions of user-created games! 🎮",
    "simulator": "Simulator games recreate real activities in exaggerated ways! 🎯",
    "vr": "VR (Virtual Reality) immerses players in 3D environments! 🥽",
    "ar": "AR (Augmented Reality) overlays digital content on the real world! 📱",
    "esports": "Esports are competitive video gaming events with professional players! 🏆",
    "streaming": "Game streaming lets you watch others play or broadcast your own gameplay! 📺",
    "twitch": "Twitch is the largest platform for live game streaming! 📺",
    "youtube gaming": "YouTube Gaming is Google's platform for gaming content! 📺",
    "discord nitro": "Nitro gives Discord users animated avatars, custom emojis everywhere, and server boosts! 💎",
    "server boost": "Server Boosts unlock perks for Discord servers like better audio and more emoji slots! 🚀",
    "gaming pc": "Gaming PCs need powerful GPUs and CPUs for high frame rates! 🖥️",
    "console": "Gaming consoles like PlayStation and Xbox offer exclusive games! 🎮",
    "nintendo switch": "Switch is Nintendo's hybrid console for home and portable gaming! 🎮",
    "playstation": "PlayStation is Sony's gaming brand with exclusive titles like God of War! 🎮",
    "xbox": "Xbox is Microsoft's gaming brand with Game Pass subscription service! 🎮",
    "steam": "Steam is the largest digital distribution platform for PC games! 🚂",
    "epic games": "Epic Games Store gives away free games weekly and made Fortnite! 🎮",
    "gog": "GOG sells DRM-free games you truly own! 🎮",
    "itch.io": "itch.io supports indie developers with fair revenue splits! 🎮",
    "game pass": "Xbox Game Pass offers hundreds of games for a monthly fee! 🎮",
    "ea play": "EA Play includes EA's library and early access to new games! 🎮",
    "ubisoft+": "Ubisoft+ gives access to Ubisoft's game library! 🎮",
    "ps plus": "PlayStation Plus is required for online play and includes monthly games! ➕",
    "nintendo online": "Nintendo Switch Online enables online play and classic game access! 🎮",
    "save file": "Save files store your game progress! 💾",
    "checkpoint": "Checkpoints let you resume from specific points if you fail! 🔄",
    "respawn": "Respawning brings you back after dying in a game! ♻️",
    "hp": "HP (Health Points) measure how much damage you can take before dying! ❤️",
    "mp": "MP (Mana/Magic Points) fuel special abilities and spells! 🔵",
    "xp": "XP (Experience Points) let you level up and grow stronger! ⭐",
    "level up": "Leveling up makes your character stronger and unlocks new abilities! ⬆️",
    "boss": "Bosses are powerful enemies that test your skills at the end of levels! 👹",
    "mini boss": "Mini-bosses are challenging enemies but not as tough as main bosses! 👾",
    "loot": "Loot is valuable items you get from defeating enemies or exploring! 💰",
    "drop": "Drops are items enemies leave behind when defeated! 🎁",
    "rare item": "Rare items are hard to find but very powerful! 💎",
    "legendary": "Legendary items are the rarest and most powerful! 🌟",
    "common": "Common items are basic and easy to find! ⚪",
    "uncommon": "Uncommon items are slightly better than common ones! 🟢",
    "rare": "Rare items are noticeably better and harder to obtain! 🔵",
    "epic": "Epic items are very powerful and quite rare! 🟣",
    "crafting": "Crafting lets you create items from gathered materials! 🔨",
    "inventory": "Inventory holds all the items you're carrying! 🎒",
    "quick slot": "Quick slots let you use items fast without opening your full inventory! ⚡",
    "hotbar": "Hotbar is a row of slots for quick access to items or abilities! 🔢",
    "cooldown": "Cooldown is the wait time before you can use an ability again! ⏱️",
    "mana": "Mana is magical energy used to cast spells! 🔮",
    "stamina": "Stamina limits how much you can run or perform actions before resting! 💪",
    "energy": "Energy fuels actions and abilities in many games! ⚡",
    "buff": "Buffs are positive effects that make you stronger! 💪",
    "debuff": "Debuffs are negative effects that weaken you! 😵",
    "dot": "DoT (Damage over Time) deals damage gradually rather than instantly! 🔥",
    "hot": "HoT (Heal over Time) restores health gradually! 💚",
    "aoe": "AoE (Area of Effect) hits multiple targets in an area! 💥",
    "single target": "Single target affects only one enemy or ally! 🎯",
    "cc": "CC (Crowd Control) disables or limits enemy actions! 🕸️",
    "stun": "Stun temporarily prevents all actions! ⭐",
    "silence": "Silence prevents ability/spell use but allows movement and attacks! 🔇",
    "root": "Root prevents movement but allows other actions! 🌱",
    "slow": "Slow reduces movement or attack speed! 🐌",
    "knockback": "Knockback pushes enemies away from you! 💨",
    "pull": "Pull brings enemies closer to you! 🧲",
    "stealth": "Stealth makes you invisible or hard to detect until you attack! 👻",
    "invisible": "Invisibility completely hides you from enemy sight! 👻",
    "camouflage": "Camouflage blends you with the environment but you can still be spotted! 🌿",
    "aggro": "Aggro (aggression) determines which player enemies will attack! 😠",
    "taunt": "Taunt forces enemies to attack you instead of allies! 📢",
    "tank": "Tanks absorb damage and protect more fragile teammates! 🛡️",
    "healer": "Healers restore health and keep the team alive! 💚",
    "dps": "DPS (Damage Per Second) classes deal damage to defeat enemies! ⚔️",
    "support": "Supports help the team with buffs, healing, or utility! 🤝",
    "assassin": "Assassins eliminate high-priority targets quickly! 🗡️",
    "mage": "Mages use magic for powerful attacks and crowd control! 🔮",
    "warrior": "Warriors are melee fighters with high health and damage! ⚔️",
    "archer": "Archers attack from range with bows or similar weapons! 🏹",
    "ranger": "Rangers use nature and ranged attacks, often have animal companions! 🌲",
    "rogue": "Rogues use stealth, traps, and precise attacks from shadows! 🗡️",
    "paladin": "Paladins are holy warriors who heal and protect allies! ✨",
    "priest": "Priests heal and support with divine magic! ✝️",
    "shaman": "Shaman use nature spirits and elemental magic! 🌿",
    "druid": "Druids shapeshift and command nature magic! 🐻",
    "necromancer": "Necromancers raise and command the dead! 💀",
    "summoner": "Summoners call creatures to fight for them! 🐺",
    "bard": "Bards support allies with music and buffs! 🎵",
    "monk": "Monks fight with martial arts and inner energy! 🥋",
    "berserker": "Berserkers rage for massive damage but lower defense! 😤",
    "gunner": "Gunners use firearms and explosives! 🔫",
    "sniper": "Snipers eliminate targets from extreme range! 🎯",
    "melee": "Melee combat happens at close range with swords, axes, fists! ⚔️",
    "ranged": "Ranged combat attacks from a distance with bows, guns, magic! 🏹",
    "magic": "Magic uses mana to cast powerful spells! 🔮",
    "physical": "Physical damage comes from weapons and strength! 💪",
    "elemental": "Elemental damage uses fire, ice, lightning, earth, wind! 🌪️",
    "fire": "Fire damage burns enemies over time! 🔥",
    "ice": "Ice damage slows and can freeze enemies solid! ❄️",
    "lightning": "Lightning damage chains between multiple targets! ⚡",
    "poison": "Poison deals damage over time and weakens enemies! ☠️",
    "earth": "Earth damage is solid and defensive, often involves rocks! 🪨",
    "wind": "Wind damage pushes enemies and enhances speed! 💨",
    "holy": "Holy damage is effective against undead and demons! ✨",
    "dark": "Dark damage corrupts and drains life! 🌑",
    "arcane": "Arcane is pure magical energy! 🔮",
    "nature": "Nature magic uses plants and animals! 🌿",
    "spirit": "Spirit magic involves souls and ethereal energy! 👻",
    "psionic": "Psionic powers use the mind for telepathy and telekinesis! 🧠",
    "chi": "Chi is life energy used in martial arts! ☯️",
    "ki": "Ki is inner energy for special techniques! ⚡",
    "chakra": "Chakra is spiritual energy in some Eastern-themed games! 🌀",
    "combo": "Combos chain multiple attacks for bonus damage! 🎯",
    "critical hit": "Critical hits deal bonus damage, often double or more! 💥",
    "headshot": "Headshots hit weak points for massive damage! 🎯",
    "weak point": "Weak points take extra damage when hit! 🎯",
    "critical": "Critical hits occur randomly or by hitting weak spots for extra damage! 💥",
    "dodge": "Dodging avoids incoming attacks completely! 🏃",
    "parry": "Parrying blocks and counters enemy attacks! 🛡️",
    "block": "Blocking reduces damage taken from attacks! 🛡️",
    "guard": "Guarding is a defensive stance reducing damage! 🛡️",
    "shield": "Shields block or reduce incoming damage! 🛡️",
    "armor": "Armor reduces physical damage taken! 🛡️",
    "resistance": "Resistance reduces damage from specific elements! 🛡️",
    "immunity": "Immunity completely prevents a damage type or status! 🛡️",
    "invincibility": "Invincibility makes you completely immune to all damage! ⭐",
    "iframe": "Invincibility frames make you briefly immune after taking damage or during rolls! ⭐",
    "super armor": "Super armor prevents flinching from hits, letting you continue attacks! 💪",
    "hyper armor": "Hyper armor is stronger super armor that can't be broken! 💪",
    "poise": "Poise determines how easily you stagger from hits! 💪",
    "stagger": "Stagger briefly stuns enemies, leaving them vulnerable! 💫",
    "stun": "Stun prevents all actions for a short duration! ⭐",
    "stunlock": "Stunlock repeatedly stuns an enemy, preventing any action! 🔒",
    "juggle": "Juggling keeps enemies airborne with consecutive attacks! 🎾",
    "air combo": "Air combos attack enemies while they're airborne! 🌪️",
    "launcher": "Launchers send enemies into the air for aerial combos! 🚀",
    "slam": "Slams smash airborne enemies into the ground! 💥",
    "throw": "Throws grab and toss enemies, often ignoring defense! 💪",
    "grapple": "Grapples grab enemies from a distance to pull them close! 🎣",
    "dash": "Dashing quickly moves you forward, often with iframes! 💨",
    "sprint": "Sprinting moves faster than walking but uses stamina! 🏃",
    "crouch": "Crouching makes you smaller and sometimes stealthier! 🦆",
    "prone": "Prone is lying flat on the ground for maximum cover! 🪖",
    "jump": "Jumping avoids ground hazards and reaches higher areas! 🦘",
    "double jump": "Double jumping allows a second jump in mid-air! 🦘",
    "triple jump": "Triple jumping allows three consecutive jumps! 🦘",
    "wall jump": "Wall jumping pushes off walls to reach higher! 🧗",
    "wall run": "Wall running lets you move along vertical surfaces! 🏃",
    "glide": "Gliding slowly descends through the air! 🪂",
    "fly": "Flying allows full aerial movement! 🦅",
    "swim": "Swimming moves through water! 🏊",
    "dive": "Diving goes underwater to explore depths! 🤿",
    "sprint swim": "Sprint swimming moves faster through water! 🏊",
    "climb": "Climbing scales vertical surfaces! 🧗",
    "ledge grab": "Ledge grabbing catches edges to pull yourself up! 🖐️",
    "rope": "Ropes can be climbed or swung across gaps! 🪢",
    "zipline": "Ziplines quickly transport you across distances! 🚡",
    "grappling hook": "Grappling hooks let you swing to distant points instantly! 🎣",
    "teleport": "Teleportation instantly moves you to a target location! ✨",
    "blink": "Blink is a short-range instant teleport! ✨",
    "recall": "Recall returns you to a previous location or base! 🏠",
    "hearthstone": "Hearthstone returns you to your home/base location! 🏠",
    "waypoint": "Waypoints are fast travel points you've discovered! 📍",
    "fast travel": "Fast travel instantly moves you to discovered locations! ⚡",
    "mount": "Mounts are creatures or vehicles for faster travel! 🐴",
    "vehicle": "Vehicles provide fast travel and sometimes combat advantages! 🚗",
    "horse": "Horses are common mounts in fantasy games! 🐴",
    "chocobo": "Chocobos are final fantasy's iconic bird mounts! 🐤",
    "car": "Cars are fast modern vehicles! 🚗",
    "motorcycle": "Motorcycles are fast, agile two-wheeled vehicles! 🏍️",
    "boat": "Boats travel across water surfaces! ⛵",
    "ship": "Ships are large vessels for ocean travel or combat! ⛵",
    "airship": "Airships fly through the sky! 🎈",
    "spaceship": "Spaceships travel through space! 🚀",
    "jetpack": "Jetpacks let you fly for limited durations! 🚀",
    "wings": "Wings allow gliding or flying! 🦋",
    "hoverboard": "Hoverboards float above the ground! 🛹",
    "glider": "Gliders descend slowly and can catch updrafts! 🪂",
    "parachute": "Parachutes slow falls from great heights! 🪂",
    "safety": "Safety equipment prevents fall damage or other hazards! ⛑️",
    "fall damage": "Fall damage hurts you when falling from heights! 💀",
    "lava": "Lava instantly kills or deals massive damage! 🌋",
    "poison water": "Poison water damages you while swimming in it! ☠️",
    "acid": "Acid rapidly damages anything touching it! 🧪",
    "spikes": "Spikes are damaging hazards on floors and walls! 🗡️",
    "trap": "Traps are hidden hazards that activate when triggered! 🕸️",
    "pitfall": "Pitfalls are hidden holes that drop you! 🕳️",
    "boulder": "Boulders roll and crush anything in their path! 🪨",
    "blade": "Spinning blades are deadly moving hazards! ⚔️",
    "fire trap": "Fire traps shoot flames when triggered! 🔥",
    "ice trap": "Ice traps freeze or slow targets! ❄️",
    "lightning trap": "Lightning traps shock targets with electricity! ⚡",
    "arrow trap": "Arrow traps shoot projectiles when triggered! 🏹",
    "spike trap": "Spike traps impale those who step on them! 🗡️",
    "gas": "Poison gas damages over time while in the area! ☠️",
    "darkness": "Darkness limits vision and may hide enemies! 🌑",
    "fog of war": "Fog of war hides unexplored areas of the map! 🌫️",
    "fog": "Fog reduces visibility range! 🌫️",
    "rain": "Rain may reduce visibility or affect certain abilities! 🌧️",
    "snow": "Snow may slow movement or affect visibility! ❄️",
    "storm": "Storms combine rain, wind, and lightning hazards! ⛈️",
    "day night": "Day/night cycles change lighting and may affect enemies! 🌅",
    "sunny": "Sunny weather provides clear visibility! ☀️",
    "weather effects": "Weather can affect gameplay, visibility, and abilities! 🌦️",
    "environmental hazard": "Environmental hazards are dangerous terrain features! ⚠️",
    "destructible": "Destructible objects can be broken for items or paths! 🪓",
    "breakable wall": "Breakable walls hide secrets when destroyed! 🧱",
    "secret": "Secrets are hidden areas, items, or paths! 🎁",
    "easter egg": "Easter eggs are hidden references or jokes by developers! 🥚",
    "hidden room": "Hidden rooms contain valuable secrets! 🚪",
    "treasure": "Treasure is valuable loot often hidden in secrets! 💰",
    "chest": "Chests contain random loot when opened! 🎁",
    "gold chest": "Gold chests contain the best rare loot! 🎁",
    "mimic": "Mimics are monsters disguised as treasure chests! 👹",
    "shop": "Shops let you buy and sell items! 🏪",
    "merchant": "Merchants sell items and buy your loot! 💰",
    "blacksmith": "Blacksmiths repair and upgrade weapons and armor! 🔨",
    "inn": "Inns restore health and sometimes save progress! 🏨",
    "save point": "Save points record your progress! 💾",
    "checkpoint": "Checkpoints let you resume if you die! 🔄",
    "bonfire": "Bonfires rest and save in soulslike games! 🔥",
    "grace": "Sites of Grace are checkpoints in Elden Ring! ✨",
    "rest": "Resting restores health and resources but may respawn enemies! 💤",
    "sleep": "Sleep skips time and restores resources! 😴",
    "wait": "Waiting passes time without moving! ⏱️",
    "time skip": "Time skips advance the clock rapidly! ⏭️",
    "pause": "Pausing freezes the game for breaks! ⏸️",
    "menu": "Menus access inventory, settings, and game options! 📋",
    "inventory": "Inventory manages your items and equipment! 🎒",
    "equipment": "Equipment is gear you're currently wearing! ⚔️",
    "weapon": "Weapons deal damage to enemies! ⚔️",
    "sword": "Swords are balanced melee weapons! ⚔️",
    "shield": "Shields block attacks and can bash enemies! 🛡️",
    "axe": "Axes deal heavy damage but may be slower! 🪓",
    "spear": "Spears have long reach for keeping enemies at distance! 🔱",
    "bow": "Bows fire arrows at range! 🏹",
    "staff": "Staves channel magical energy for spellcasting! 🪄",
    "wand": "Wands cast quick magical projectiles! 🪄",
    "dagger": "Daggers are fast, light weapons for quick strikes! 🗡️",
    "hammer": "Hammers deal massive blunt damage but are slow! 🔨",
    "mace": "Maces are blunt weapons effective against armor! 🔨",
    "flail": "Flails are chain weapons that can bypass shields! 🔗",
    "whip": "Whips have long range and can hit multiple enemies! 🐂",
    "claws": "Claws are fast slashing weapons! 🐾",
    "fist": "Fists are unarmed combat weapons! 👊",
    "gauntlet": "Gauntlets enhance unarmed combat damage! 🥊",
    "katana": "Katanas are curved Japanese swords with fast slashes! 🗡️",
    "greatsword": "Greatswords are massive two-handed swords! ⚔️",
    "rapier": "Rapiers are thin thrusting swords for precise strikes! 🗡️",
    "scythe": "Scythes are reaping weapons with wide arcs! 🌾",
    "halberd": "Halberds are poleaxes combining spear and axe! 🔱",
    "glaive": "Glaives are bladed polearms! 🔱",
    "crossbow": "Crossbows are mechanical bows with high damage but slow reload! 🏹",
    "pistol": "Pistols are one-handed firearms! 🔫",
    "rifle": "Rifles are two-handed long guns! 🔫",
    "shotgun": "Shotguns deal massive damage at close range! 🔫",
    "machine gun": "Machine guns fire rapidly with large magazines! 🔫",
    "rocket launcher": "Rocket launchers fire explosive projectiles! 🚀",
    "grenade": "Grenades are thrown explosives! 💣",
    "bomb": "Bombs deal area damage when detonated! 💣",
    "mine": "Mines explode when enemies step on them! 💣",
    "c4": "C4 is remote-detonated explosive! 💣",
    "turret": "Turrets are automated defensive guns! 🔫",
    "sentry": "Sentries are automated defensive units! 🤖",
    "drone": "Drones are remote-controlled or autonomous units! 🛸",
    "mech": "Mechs are piloted robotic combat suits! 🤖",
    "robot": "Robots are mechanical automatons! 🤖",
    "golem": "Golems are animated constructs often made of stone or metal! 🪨",
    "elemental": "Elementals are spirits of natural elements! 🔥",
    "undead": "Undead are reanimated corpses like zombies and skeletons! 🧟",
    "skeleton": "Skeletons are animated bones vulnerable to blunt damage! 💀",
    "zombie": "Zombies are reanimated corpses that feast on the living! 🧟",
    "vampire": "Vampires drink blood and have supernatural powers! 🧛",
    "werewolf": "Werewolves transform under the full moon! 🐺",
    "ghost": "Ghosts are spirits of the dead with ethereal powers! 👻",
    "spirit": "Spirits are non-physical supernatural entities! 👻",
    "demon": "Demons are evil beings from other dimensions! 😈",
    "devil": "Devils are powerful evil entities! 👿",
    "angel": "Angels are divine messengers and warriors! 👼",
    "god": "Gods are all-powerful divine beings! ☀️",
    "dragon": "Dragons are massive flying reptiles that breathe fire! 🐉",
    "wyvern": "Wyverns are dragons with two legs and wings as arms! 🐉",
    "drake": "Drakes are lesser dragons without flight! 🐉",
    "wyrm": "Wyrms are serpentine dragons! 🐍",
    "goblin": "Goblins are small, mischievous humanoids! 👺",
    "orc": "Orcs are strong, warlike humanoids! 🐗",
    "troll": "Trolls are large, regenerating humanoids! 👹",
    "ogre": "Ogres are large, strong but dim humanoids! 👹",
    "giant": "Giants are massive humanoids of great strength! 🗿",
    "elf": "Elves are graceful, long-lived humanoids with pointed ears! 🧝",
    "dwarf": "Dwarves are short, stocky master craftsmen and miners! ⛏️",
    "halfling": "Halflings are small humanoids resembling children! 🧒",
    "gnome": "Gnomes are small, clever inventors and pranksters! 👴",
    "fairy": "Fairies are tiny, magical winged creatures! 🧚",
    "pixie": "Pixies are mischievous fairy-like creatures! ✨",
    "sprite": "Sprites are nature spirits appearing as small glowing beings! ✨",
    "imp": "Imps are small, mischievous demons! 👿",
    "slime": "Slimes are gelatinous monsters of various colors! 🟢",
    "jelly": "Jellies are like slimes but sometimes more dangerous! 🟣",
    "cube": "Gelatinous cubes are D&D monsters that dissolve organic matter! 🟩",
    "blob": "Blobs are amorphous monsters that absorb things! 🟤",
    "mimic": "Mimics disguise themselves as objects to ambush prey! 📦",
    "rust monster": "Rust monsters eat metal, terrifying adventurers! 🦀",
    "beholder": "Beholders are floating heads with eye stalks that shoot magic rays! 👁️",
    "mind flayer": "Mind flayers are psychic octopus-headed humanoids that eat brains! 🦑",
    "lich": "Liches are powerful undead spellcasters who bound their souls to phylacteries! 🧙",
    "vampire lord": "Vampire lords are ancient and powerful vampires! 🧛",
    "werewolf alpha": "Alpha werewolves lead packs and are stronger than normal werewolves! 🐺",
    "demon lord": "Demon lords rule layers of the abyss! 😈",
    "archdevil": "Archdevils rule the nine hells! 👿",
    "celestial": "Celestials are good-aligned beings from upper planes! ✨",
    "fiend": "Fiends are evil beings from lower planes! 🔥",
    "aberration": "Aberrations are alien entities from beyond normal reality! 🌀",
    "construct": "Constructs are animated objects given life by magic! 🤖",
    "monstrosity": "Monstrosities are unnatural creatures created by magic! 🧪",
    "ooze": "Oozes are mindless, amorphous creatures that absorb things! 🟢",
    "plant": "Plant creatures are animated vegetation! 🌿",
    "beast": "Beasts are natural animals! 🐺",
    "humanoid": "Humanoids are bipedal creatures similar to humans! 👤",
    "giant class": "Giant-class creatures include ogres, trolls, giants! 🗿",
    "reptilian": "Reptilian creatures include lizardfolk, yuan-ti, and kobolds! 🦎",
    "amphibian": "Amphibian creatures include bullywugs and frog people! 🐸",
    "avian": "Avian creatures include aarakocra and kenku! 🦅",
    "aquatic": "Aquatic creatures live in water: merfolk, sahuagin, etc! 🐟",
    "arachnid": "Arachnids include giant spiders, driders, and ettercaps! 🕷️",
    "insectoid": "Insectoid creatures include thri-kreen and formians! 🐜",
    "crustacean": "Crustaceans include Chuul and giant crabs! 🦀",
    "mollusk": "Mollusks include flailsnails and oysterlings! 🦪",
    "worm": "Worms include purple worms and death worms! 🐛",
    "serpent": "Serpents include nagas and guardian nagas! 🐍",
    "hydra": "Hydras have multiple heads that regrow when cut off! 🐉",
    "chimera": "Chimeras have parts from multiple animals! 🦁",
    "manticore": "Manticores have a lion body, human face, scorpion tail! 🦁",
    "griffin": "Griffins have eagle head/front and lion body/back! 🦅",
    "hippogriff": "Hippogriffs have eagle front and horse back! 🦅",
    "pegasus": "Pegasus is a winged horse! 🐴",
    "unicorn": "Unicorns are horses with healing magic and one horn! 🦄",
    "nightmare": "Nightmares are evil, flaming black horses! 🔥",
    "hell hound": "Hell hounds are fire-breathing demonic dogs! 🐕",
    "winter wolf": "Winter wolves are intelligent, cold-breathing white wolves! ❄️",
    "dire wolf": "Dire wolves are massive prehistoric wolves! 🐺",
    "weretiger": "Weretigers are tiger lycanthropes! 🐅",
    "werebear": "Werebears are bear lycanthropes! 🐻",
    "wereboar": "Wereboars are boar lycanthropes! 🐗",
    "wererat": "Wererats are rat lycanthropes! 🐀",
    "wereraven": "Wereravens are raven lycanthropes! 🦅",
    "jackalwere": "Jackalweres are jackal lycanthropes! 🐕",
    "hyenadon": "Hyenadons are prehistoric hyena-like predators! 🦴",
    "saber tooth": "Saber-toothed cats are prehistoric predators with long fangs! 🐱",
    "mammoth": "Mammoths are woolly elephants from the ice age! 🐘",
    "mastodon": "Mastodons are ancient relatives of elephants! 🐘",
    "dinosaur": "Dinosaurs are ancient reptiles that ruled Earth millions of years ago! 🦕",
    "t-rex": "Tyrannosaurus Rex was a massive carnivorous dinosaur! 🦖",
    "triceratops": "Triceratops had three horns and a frilled collar! 🦕",
    "velociraptor": "Velociraptors were small, intelligent pack hunters! 🦖",
    "stegosaurus": "Stegosaurus had plates on its back and spiked tail! 🦕",
    "brontosaurus": "Brontosaurus (Apatosaurus) was a massive long-necked herbivore! 🦕",
    "pterodactyl": "Pterodactyls were flying reptiles, not dinosaurs! 🦅",
    "plesiosaur": "Plesiosaurs were long-necked marine reptiles! 🐢",
    "mosasaur": "Mosasaurs were giant marine predators! 🦎",
    "ichthyosaur": "Ichthyosaurs were dolphin-like marine reptiles! 🐬",
    "pteranodon": "Pteranodons were large flying reptiles with crests! 🦅",

    # === FUN FACTS (50+ entries) ===
    "banana": "Bananas are technically berries, but strawberries aren't! 🍌",
    "honey": "Honey never spoils - edible honey was found in 3000-year-old Egyptian tombs! 🍯",
    "octopus": "Octopuses have three hearts, blue blood, and nine brains! 🐙",
    "sloth": "Sloths can hold their breath longer than dolphins - up to 40 minutes! 🦥",
    "flamingo": "Flamingos are naturally white - their diet turns them pink! 🦩",
    "koala": "Koalas have fingerprints almost identical to humans! 🐨",
    "otter": "Sea otters hold hands while sleeping so they don't drift apart! 🦦",
    "penguin": "Male penguins propose to females with pebbles! 🐧",
    "elephant": "Elephants are the only mammals that can't jump! 🐘",
    "blue whale": "A blue whale's heart is the size of a small car! 🐋",
    "shark": "Sharks existed before trees! 🦈",
    "jellyfish": "Jellyfish are 95% water and have no brain, heart, or bones! 🪼",
    "bee": "Bees can recognize human faces! 🐝",
    "butterfly": "Butterflies taste with their feet! 🦋",
    "axolotl": "Axolotls can regenerate their heart, spine, and parts of their brain! 🦎",
    "platypus": "Platypuses are mammals that lay eggs and have venomous spurs! 🦫",
    "hummingbird": "Hummingbirds are the only birds that can fly backward! 🐦",
    "owl": "Owls can't move their eyes, so they turn their heads up to 270 degrees! 🦉",
    "bat": "Bats are the only mammals that can truly fly! 🦇",
    "cheetah": "Cheetahs can accelerate faster than most sports cars! 🐆",
    "chicken": "Chickens are the closest living relatives to T-Rex! 🐔",
    "pig": "Pigs are smarter than dogs and can play video games! 🐷",
    "cow": "Cows have best friends and get stressed when separated! 🐄",
    "horse": "Horses can sleep standing up but need to lie down for REM sleep! 🐴",
    "cat": "Cats spend 70% of their lives sleeping! 🐱",
    "dog": "Dogs have a sense of time and miss you when you're gone! 🐕",
    "goldfish": "Goldfish have memories longer than 3 seconds - they can remember for months! 🐠",

    # === GENERAL KNOWLEDGE & GEOGRAPHY (50+ entries) ===
    "capital of france": "Paris is the capital of France, known as the City of Light! 🇫🇷",
    "capital of germany": "Berlin is the capital of Germany, famous for its history and culture! 🇩🇪",
    "capital of uk": "London is the capital of the United Kingdom, home to Big Ben! 🇬🇧",
    "capital of usa": "Washington D.C. is the capital of the United States! 🇺🇸",
    "capital of japan": "Tokyo is the capital of Japan, the world's most populous metropolis! 🇯🇵",
    "capital of canada": "Ottawa is the capital of Canada! 🇨🇦",
    "capital of australia": "Canberra is the capital of Australia, not Sydney or Melbourne! 🇦🇺",
    "largest country": "Russia is the largest country by land area at 17 million km²! 🇷🇺",
    "smallest country": "Vatican City is the smallest country at just 0.44 km²! 🇻🇦",
    "most populous country": "India overtook China as the most populous country in 2023! 🇮🇳",
    "largest ocean": "The Pacific Ocean is the largest, covering 30% of Earth's surface! 🌊",
    "highest mountain": "Mount Everest is the highest at 8,849 meters (29,032 ft)! 🏔️",
    "longest river": "The Nile was traditionally considered longest, but the Amazon may be longer! 🏞️",
    "great wall": "The Great Wall of China is over 21,000 km long! 🇨🇳",
    "eiffel tower": "The Eiffel Tower was supposed to be dismantled after 20 years! 🇫🇷",
    "statue of liberty": "The Statue of Liberty was a gift from France to the US! 🗽",
    "machu picchu": "Machu Picchu was built around 1450 but abandoned a century later! 🇵🇪",
    "pyramids": "The Great Pyramid of Giza was the tallest building for 3,800 years! 🇪🇬",

    # === TECHNOLOGY & PROGRAMMING (100+ entries) ===
    "cpu": "The CPU (Central Processing Unit) is the brain of a computer, executing instructions! 🧠",
    "gpu": "The GPU (Graphics Processing Unit) handles visual rendering and parallel processing! 🎨",
    "ram": "RAM (Random Access Memory) is volatile memory used for active tasks! 💾",
    "ssd": "SSDs (Solid State Drives) are faster than HDDs with no moving parts! ⚡",
    "motherboard": "The motherboard connects all computer components together! 🔌",
    "linux": "Linux is an open-source operating system popular with developers! 🐧",
    "windows": "Windows is Microsoft's popular desktop operating system! 🪟",
    "macos": "macOS is Apple's desktop operating system! 🍎",
    "python": "Python is a readable, versatile programming language popular for AI and data science! 🐍",
    "javascript": "JavaScript adds interactivity to web pages and runs on servers with Node.js! 📜",
    "java": "Java is a portable language running on the JVM - 'write once, run anywhere'! ☕",
    "c++": "C++ is a fast, powerful language used for games and system software! ➕",
    "rust": "Rust provides memory safety without garbage collection! 🦀",
    "html": "HTML (HyperText Markup Language) creates the structure of web pages! 🌐",
    "css": "CSS (Cascading Style Sheets) styles web page appearance! 🎨",
    "api": "API (Application Programming Interface) lets different software communicate! 🔌",
    "git": "Git is the most popular version control system! 🌳",
    "docker": "Docker containers package applications with their dependencies! 🐳",
    "kubernetes": "Kubernetes (K8s) orchestrates container deployments at scale! ☸️",
    "cloud": "Cloud computing delivers services over the internet! ☁️",
    "aws": "Amazon Web Services is the largest cloud provider! 🌩️",
    "blockchain": "Blockchain is a decentralized, distributed ledger technology! ⛓️",
    "bitcoin": "Bitcoin was the first decentralized cryptocurrency, created by Satoshi Nakamoto! ₿",
    "ethereum": "Ethereum is a blockchain platform famous for smart contracts! ⟠",

    # === SPACE & ASTRONOMY (50+ entries) ===
    "milky way": "The Milky Way is our home galaxy, containing 100-400 billion stars! 🌌",
    "andromeda": "Andromeda is our nearest major galaxy, 2.5 million light-years away! 🌌",
    "black hole": "A black hole is a region where gravity is so strong that nothing can escape! 🕳️",
    "supernova": "A supernova is a powerful explosion marking the end of a massive star's life! 💥",
    "neutron star": "Neutron stars are incredibly dense - a teaspoon weighs about 6 billion tons! ⚛️",
    "exoplanet": "Exoplanets are planets orbiting stars other than our Sun! 🪐",
    "mars": "Mars is the fourth planet, known as the Red Planet! 🔴",
    "jupiter": "Jupiter is the largest planet in our solar system! 🪐",
    "saturn": "Saturn is famous for its beautiful ring system! 💍",
    "pluto": "Pluto was reclassified as a dwarf planet in 2006, but it's still loved! ❄️",
    "voyager 1": "Voyager 1 is the most distant human-made object, 24 billion km away! 🛰️",
    "jwst": "The James Webb Space Telescope is the most powerful space telescope! 🔭",

    # === HISTORY (50+ entries) ===
    "world war 1": "WWI lasted from 1914 to 1918, also known as the Great War! ⚔️",
    "world war 2": "WWII lasted from 1939 to 1945, the deadliest conflict in history! ⚔️",
    "industrial revolution": "The Industrial Revolution began in Britain in the 18th century! 🏭",
    "french revolution": "The French Revolution began in 1789, leading to the rise of Napoleon! 🇫🇷",
    "ancient rome": "Rome grew from a small town to an empire covering much of Europe! 🏛️",
    "ancient egypt": "Ancient Egypt is famous for pharaohs, pyramids, and hieroglyphs! 🇪🇬",
    "renaissance": "The Renaissance was a cultural rebirth from the 14th-17th centuries! 🎨",
    "moon landing": "Apollo 11 landed on the Moon July 20, 1969! 🌙",
    "magna carta": "The Magna Carta (1215) limited English royal power! 📜",
    "nelson mandela": "Nelson Mandela was a South African leader who fought against apartheid! 🇿🇦",
    "martin luther king": "MLK was a leader in the American civil rights movement! ✊🏾",
    "gandhi": "Mahatma Gandhi led India to independence through nonviolent protest! 🇮🇳",

    # === RIDDLES & PUZZLES (50+ entries) ===
    "riddle me this": "I have keys but no locks. I have a space but no room. You can enter, but never leave. What am I? (A keyboard! ⌨️)",
    "riddle": "What has to be broken before you can use it? (An egg! 🥚)",
    "brain teaser": "What month of the year has 28 days? (All of them! 📅)",
    "easy riddle": "What has hands but can't clap? (A clock! 🕰️)",
    "hard riddle": "What is full of holes but still holds water? (A sponge! 🧽)",

    # === QUOTES & MOTIVATION (50+ entries) ===
    "quote": "'Imagination is more important than knowledge.' - Albert Einstein 🧠",
    "motivation": "The only way to do great work is to love what you do! ❤️",
    "inspirational": "Believe you can and you're halfway there! 🌟",
    "success": "Success is not final, failure is not fatal: it is the courage to continue that counts. 📈",
    "einstein quote": "'Learn from yesterday, live for today, hope for tomorrow.' 🎓",

    # === HEALTH & HUMAN BODY (50+ entries) ===
    "human brain": "The human brain generates about 20 watts of electrical power - enough to power a dim light bulb! 🧠",
    "blood": "An adult human has about 5 liters of blood! 🩸",
    "bones": "Adults have 206 bones, but babies are born with about 300! 🦴",
    "heartbeat": "Your heart beats about 100,000 times a day! 💓",
    "skin": "The skin is the body's largest organ! 🖐️",
    "dna": "Human DNA is 99.9% identical from person to person! 🧬",
    "water in body": "The human body is about 60% water! 💧",
    "eyes": "Human eyes can distinguish about 10 million different colors! 👁️",

    # === FOOD & COOKING (50+ entries) ===
    "pizza": "The first pizza is believed to have been made in Naples, Italy! 🍕",
    "chocolate": "Chocolate was once used as currency by the Aztecs! 🍫",
    "coffee": "Coffee is the world's second most traded commodity after oil! ☕",
    "tea": "Tea is the most consumed beverage in the world after water! 🍵",
    "apple": "There are over 7,500 varieties of apples grown worldwide! 🍎",
    "sushi": "Sushi originally started as a way to preserve fish in fermented rice! 🍣",
    "spicy": "The 'heat' in chili peppers comes from a chemical called capsaicin! 🌶️",
    "vitamin c": "Oranges are famous for Vitamin C, but bell peppers actually have more! 🍊",

    # === LIFE ADVICE (50+ entries) ===
    "advice": "Always be kind, for everyone you meet is fighting a hard battle. ✨",
    "life tip": "Drink plenty of water and get enough sleep - your body will thank you! 💧",
    "happiness": "Happiness is not something ready-made. It comes from your own actions. 😊",
    "learning": "Never stop learning, because life never stops teaching! 📚"
}

def analyze_and_reply_mini_ai(question):
    """Mini AI logic to analyze and reply to user questions locally"""
    q = question.lower()
    
    # 1. Keywords mapping
    for key, response in MINI_AI_KNOWLEDGE.items():
        if key in q:
            return response

    # 2. Simple Math Analysis
    math_pattern = re.search(r"(\d+)\s*([\+\-\*\/])\s*(\d+)", q)
    if math_pattern:
        try:
            num1 = int(math_pattern.group(1))
            op = math_pattern.group(2)
            num2 = int(math_pattern.group(3))
            if op == '+': res = num1 + num2
            elif op == '-': res = num1 - num2
            elif op == '*': res = num1 * num2
            elif op == '/': res = num1 / num2 if num2 != 0 else "undefined"
            return f"I analyzed your math question: {num1} {op} {num2} = {res}"
        except:
            pass

    # 3. Fallback for unknown questions
    if "?" in q:
        return "That's an interesting question! I don't have a specific local answer for that yet, but I'm learning every day. Try asking something about my features!"
        
    return None

async def get_ai_response_discord(user_id, message_content, discord_conversations, personality_prompt, ollama_model, max_tokens=80):
    """Get AI response for Discord with conversation memory"""
    # Try Mini AI first
    mini_response = analyze_and_reply_mini_ai(message_content)
    if mini_response:
        return mini_response

    try:
        user_id_str = str(user_id)
        if user_id_str not in discord_conversations:
            discord_conversations[user_id_str] = []
        
        discord_conversations[user_id_str].append({"role": "user", "content": message_content})
        
        if len(discord_conversations[user_id_str]) > 5:
            discord_conversations[user_id_str] = discord_conversations[user_id_str][-5:]

        # 1. Try OpenAI if key exists
        openai_key = os.getenv("OPENAI_API_KEY")
        if openai_key and openai_key != "your_openai_api_key_here":
            try:
                headers = {"Authorization": f"Bearer {openai_key}", "Content-Type": "application/json"}
                payload = {
                    "model": "gpt-3.5-turbo",
                    "messages": [{"role": "system", "content": personality_prompt}] + discord_conversations[user_id_str],
                    "max_tokens": max_tokens
                }
                async with httpx.AsyncClient() as client:
                    resp = await client.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=10)
                    if resp.status_code == 200:
                        reply = resp.json()['choices'][0]['message']['content'].strip()
                        discord_conversations[user_id_str].append({"role": "assistant", "content": reply})
                        return reply
            except Exception as e:
                print(f"DEBUG: OpenAI error: {e}")

        # 2. Fallback to Pollinations AI (Free)
        try:
            pollinations_url = f"https://text.pollinations.ai/{personality_prompt} {message_content}"
            async with httpx.AsyncClient() as client:
                resp = await client.get(pollinations_url, timeout=10)
                if resp.status_code == 200:
                    reply = resp.text.strip()
                    discord_conversations[user_id_str].append({"role": "assistant", "content": reply})
                    return reply
        except Exception as p_err:
            print(f"DEBUG: Pollinations fallback error: {p_err}")

        # 3. Fallback to Ollama
        try:
            context_text = "\n".join([f"{'User' if m['role'] == 'user' else 'You'}: {m['content']}" for m in discord_conversations[user_id_str][:-1]])
            current_message = discord_conversations[user_id_str][-1]["content"]
            
            ollama_prompt = f"{personality_prompt}\n\nPrevious conversation:\n{context_text}\n\nUser just said: {current_message}\n\nReply naturally:"
            
            resp = requests.post(
                f"{os.getenv('OLLAMA_HOST', 'http://localhost:11434')}/api/generate",
                json={
                    "model": ollama_model,
                    "prompt": ollama_prompt,
                    "stream": False,
                    "options": {"num_predict": max_tokens}
                },
                timeout=10
            )
            if resp.status_code == 200:
                reply = resp.json().get('response', '').strip()
                discord_conversations[user_id_str].append({"role": "assistant", "content": reply})
                return reply
        except Exception as o_err:
            print(f"DEBUG: Ollama fallback error: {o_err}")
        
        return "I'm here! How can I help you today? 😊" 

    except Exception as e:
        print(f"DEBUG: AI response error: {e}")
        return None
